import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts, do not edit by hand.
/** Scheduled 2026-08-07 (extra hard). 5×5, 4-digit code, intended 11-mirror solution (44% density), no ≤6-mirror shortcut. */
export const PUZZLE_047: Puzzle = {
  id: 47,
  code: "4801",
  gridSize: 5,
  source: { x: 2, y: 4, direction: "up" },
  flag: { x: 2, y: 0 },
  numbers: [
    { value: 4, x: 0, y: 3 },
    { value: 8, x: 1, y: 4 },
    { value: 0, x: 3, y: 2 },
    { value: 1, x: 4, y: 1 },
  ],
  obstacles: [
    { x: 4, y: 3 },
    { x: 3, y: 1 },
  ],
};
