import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts — do not edit by hand.
/** Scheduled 2026-07-26 (extra hard). 6×6, 6-digit code, intended 15-mirror solution (42% density), no ≤4-mirror shortcut. */
export const PUZZLE_035: Puzzle = {
  id: 35,
  code: "354273",
  gridSize: 6,
  source: { x: 0, y: 3, direction: "right" },
  flag: { x: 2, y: 5 },
  numbers: [
    { value: 3, x: 3, y: 1 },
    { value: 5, x: 4, y: 2 },
    { value: 4, x: 3, y: 0 },
    { value: 2, x: 5, y: 2 },
    { value: 7, x: 0, y: 4 },
    { value: 3, x: 1, y: 5 },
  ],
  obstacles: [
    { x: 2, y: 4 },
    { x: 1, y: 0 },
  ],
};
