import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts, do not edit by hand.
/** Scheduled 2026-07-25 (extra hard). 6×6, 4-digit code, intended 16-mirror solution (44% density), no ≤4-mirror shortcut. */
export const PUZZLE_034: Puzzle = {
  id: 34,
  code: "1143",
  gridSize: 6,
  source: { x: 0, y: 4, direction: "right" },
  flag: { x: 2, y: 0 },
  numbers: [
    { value: 1, x: 2, y: 2 },
    { value: 1, x: 4, y: 0 },
    { value: 4, x: 4, y: 2 },
    { value: 3, x: 0, y: 3 },
  ],
  obstacles: [
    { x: 3, y: 2 },
    { x: 3, y: 5 },
  ],
};
