import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts. Do not edit by hand.
/** Scheduled 2026-09-22 (extra hard). 8×8, 5-digit code, intended 20-mirror solution (31% density), no ≤3-mirror shortcut. */
export const PUZZLE_093: Puzzle = {
  id: 93,
  code: "68440",
  gridSize: 8,
  source: { x: 3, y: 4, direction: "right" },
  flag: { x: 5, y: 0 },
  numbers: [
    { value: 6, x: 3, y: 3 },
    { value: 8, x: 2, y: 1 },
    { value: 4, x: 2, y: 2 },
    { value: 4, x: 6, y: 3 },
    { value: 0, x: 6, y: 0 },
  ],
  obstacles: [
    { x: 3, y: 0 },
    { x: 0, y: 1 },
    { x: 1, y: 0 },
    { x: 5, y: 5 },
  ],
};
