import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts. Do not edit by hand.
/** Scheduled 2026-09-19 (extra hard). 5×5, 6-digit code, intended 10-mirror solution (40% density), no ≤7-mirror shortcut. */
export const PUZZLE_090: Puzzle = {
  id: 90,
  code: "846174",
  gridSize: 5,
  source: { x: 1, y: 4, direction: "up" },
  flag: { x: 0, y: 2 },
  numbers: [
    { value: 8, x: 2, y: 4 },
    { value: 4, x: 4, y: 2 },
    { value: 6, x: 2, y: 1 },
    { value: 1, x: 2, y: 3 },
    { value: 7, x: 3, y: 2 },
    { value: 4, x: 2, y: 0 },
  ],
  obstacles: [
    { x: 4, y: 4 },
    { x: 2, y: 2 },
  ],
};
