import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts — do not edit by hand.
/** Scheduled 2026-08-18 (extra hard). 7×7, 5-digit code, intended 18-mirror solution (37% density), no ≤3-mirror shortcut. */
export const PUZZLE_058: Puzzle = {
  id: 58,
  code: "62902",
  gridSize: 7,
  source: { x: 3, y: 6, direction: "up" },
  flag: { x: 0, y: 2 },
  numbers: [
    { value: 6, x: 4, y: 4 },
    { value: 2, x: 5, y: 2 },
    { value: 9, x: 2, y: 5 },
    { value: 0, x: 1, y: 2 },
    { value: 2, x: 0, y: 1 },
  ],
  obstacles: [
    { x: 3, y: 1 },
    { x: 6, y: 2 },
    { x: 5, y: 4 },
  ],
};
