import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts — do not edit by hand.
/** Scheduled 2026-09-01 (extra hard). 8×8, 6-digit code, intended 25-mirror solution (39% density), no ≤3-mirror shortcut. */
export const PUZZLE_072: Puzzle = {
  id: 72,
  code: "946508",
  gridSize: 8,
  source: { x: 1, y: 4, direction: "right" },
  flag: { x: 3, y: 5 },
  numbers: [
    { value: 9, x: 3, y: 3 },
    { value: 4, x: 5, y: 5 },
    { value: 6, x: 7, y: 3 },
    { value: 5, x: 3, y: 2 },
    { value: 0, x: 1, y: 2 },
    { value: 8, x: 0, y: 2 },
  ],
  obstacles: [
    { x: 7, y: 6 },
    { x: 0, y: 4 },
    { x: 5, y: 0 },
    { x: 6, y: 7 },
  ],
};
