import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts — do not edit by hand.
/** Scheduled 2026-07-23 (extra hard). 5×5, 5-digit code, intended 13-mirror solution (52% density), no ≤6-mirror shortcut. */
export const PUZZLE_032: Puzzle = {
  id: 32,
  code: "32125",
  gridSize: 5,
  source: { x: 0, y: 3, direction: "right" },
  flag: { x: 2, y: 0 },
  numbers: [
    { value: 3, x: 0, y: 2 },
    { value: 2, x: 2, y: 2 },
    { value: 1, x: 3, y: 4 },
    { value: 2, x: 4, y: 2 },
    { value: 5, x: 3, y: 0 },
  ],
  obstacles: [
    { x: 3, y: 1 },
    { x: 2, y: 1 },
  ],
};
