import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts. Do not edit by hand.
/** Scheduled 2026-08-28 (extra hard). 8×8, 5-digit code, intended 22-mirror solution (34% density), no ≤3-mirror shortcut. */
export const PUZZLE_068: Puzzle = {
  id: 68,
  code: "18739",
  gridSize: 8,
  source: { x: 4, y: 7, direction: "up" },
  flag: { x: 1, y: 6 },
  numbers: [
    { value: 1, x: 3, y: 6 },
    { value: 8, x: 2, y: 5 },
    { value: 7, x: 3, y: 1 },
    { value: 3, x: 3, y: 4 },
    { value: 9, x: 3, y: 7 },
  ],
  obstacles: [
    { x: 5, y: 5 },
    { x: 0, y: 0 },
    { x: 0, y: 3 },
    { x: 6, y: 5 },
  ],
};
