import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts, do not edit by hand.
/** Scheduled 2026-08-08 (extra hard). 6×6, 4-digit code, intended 16-mirror solution (44% density), no ≤4-mirror shortcut. */
export const PUZZLE_048: Puzzle = {
  id: 48,
  code: "3972",
  gridSize: 6,
  source: { x: 0, y: 4, direction: "right" },
  flag: { x: 0, y: 2 },
  numbers: [
    { value: 3, x: 1, y: 5 },
    { value: 9, x: 4, y: 2 },
    { value: 7, x: 5, y: 1 },
    { value: 2, x: 4, y: 0 },
  ],
  obstacles: [
    { x: 5, y: 4 },
    { x: 1, y: 1 },
  ],
};
