import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts, do not edit by hand.
/** Scheduled 2026-07-14 (extra hard). 5×5, 4-digit code, intended 12-mirror solution (48% density), no ≤6-mirror shortcut. */
export const PUZZLE_023: Puzzle = {
  id: 23,
  code: "2899",
  gridSize: 5,
  source: { x: 2, y: 0, direction: "down" },
  flag: { x: 2, y: 4 },
  numbers: [
    { value: 2, x: 1, y: 0 },
    { value: 8, x: 4, y: 1 },
    { value: 9, x: 3, y: 2 },
    { value: 9, x: 0, y: 3 },
  ],
  obstacles: [
    { x: 3, y: 1 },
    { x: 3, y: 3 },
  ],
};
