import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts. Do not edit by hand.
/** Scheduled 2026-09-25 (extra hard). 5×5, 5-digit code, intended 10-mirror solution (40% density), no ≤6-mirror shortcut. */
export const PUZZLE_096: Puzzle = {
  id: 96,
  code: "93713",
  gridSize: 5,
  source: { x: 4, y: 1, direction: "left" },
  flag: { x: 1, y: 4 },
  numbers: [
    { value: 9, x: 3, y: 0 },
    { value: 3, x: 3, y: 3 },
    { value: 7, x: 2, y: 3 },
    { value: 1, x: 1, y: 2 },
    { value: 3, x: 0, y: 3 },
  ],
  obstacles: [
    { x: 4, y: 4 },
    { x: 1, y: 1 },
  ],
};
