import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts — do not edit by hand.
/** Scheduled 2026-08-30 (extra hard). 7×7, 5-digit code, intended 20-mirror solution (41% density), no ≤3-mirror shortcut. */
export const PUZZLE_070: Puzzle = {
  id: 70,
  code: "52764",
  gridSize: 7,
  source: { x: 3, y: 0, direction: "down" },
  flag: { x: 3, y: 6 },
  numbers: [
    { value: 5, x: 1, y: 3 },
    { value: 2, x: 0, y: 4 },
    { value: 7, x: 4, y: 2 },
    { value: 6, x: 2, y: 1 },
    { value: 4, x: 2, y: 6 },
  ],
  obstacles: [
    { x: 0, y: 6 },
    { x: 3, y: 5 },
    { x: 5, y: 1 },
  ],
};
