import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts — do not edit by hand.
/** Scheduled 2026-08-21 (extra hard). 7×7, 5-digit code, intended 20-mirror solution (41% density), no ≤3-mirror shortcut. */
export const PUZZLE_061: Puzzle = {
  id: 61,
  code: "18527",
  gridSize: 7,
  source: { x: 4, y: 0, direction: "down" },
  flag: { x: 2, y: 6 },
  numbers: [
    { value: 1, x: 5, y: 5 },
    { value: 8, x: 2, y: 3 },
    { value: 5, x: 3, y: 1 },
    { value: 2, x: 5, y: 0 },
    { value: 7, x: 0, y: 1 },
  ],
  obstacles: [
    { x: 2, y: 4 },
    { x: 6, y: 6 },
    { x: 1, y: 5 },
  ],
};
