import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts. Do not edit by hand.
/** Scheduled 2026-08-23 (extra hard). 7×7, 6-digit code, intended 20-mirror solution (41% density), no ≤3-mirror shortcut. */
export const PUZZLE_063: Puzzle = {
  id: 63,
  code: "579426",
  gridSize: 7,
  source: { x: 2, y: 2, direction: "right" },
  flag: { x: 2, y: 6 },
  numbers: [
    { value: 5, x: 5, y: 6 },
    { value: 7, x: 6, y: 5 },
    { value: 9, x: 3, y: 0 },
    { value: 4, x: 2, y: 1 },
    { value: 2, x: 1, y: 3 },
    { value: 6, x: 0, y: 4 },
  ],
  obstacles: [
    { x: 5, y: 0 },
    { x: 1, y: 2 },
    { x: 6, y: 1 },
  ],
};
