import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts, do not edit by hand.
/** Scheduled 2026-07-19 (extra hard). 9×9, 8-digit code, intended 32-mirror solution (40% density), no ≤3-mirror shortcut. */
export const PUZZLE_028: Puzzle = {
  id: 28,
  code: "92235722",
  gridSize: 9,
  source: { x: 1, y: 0, direction: "down" },
  flag: { x: 6, y: 0 },
  numbers: [
    { value: 9, x: 0, y: 2 },
    { value: 2, x: 0, y: 7 },
    { value: 2, x: 4, y: 8 },
    { value: 3, x: 5, y: 6 },
    { value: 5, x: 5, y: 2 },
    { value: 7, x: 6, y: 3 },
    { value: 2, x: 7, y: 6 },
    { value: 2, x: 8, y: 6 },
  ],
  obstacles: [
    { x: 7, y: 1 },
    { x: 5, y: 5 },
    { x: 3, y: 2 },
    { x: 3, y: 1 },
    { x: 7, y: 4 },
  ],
};
