import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts — do not edit by hand.
/** Scheduled 2026-07-21 (extra hard). 6×6, 5-digit code, intended 15-mirror solution (42% density), no ≤4-mirror shortcut. */
export const PUZZLE_030: Puzzle = {
  id: 30,
  code: "31780",
  gridSize: 6,
  source: { x: 5, y: 1, direction: "left" },
  flag: { x: 3, y: 5 },
  numbers: [
    { value: 3, x: 3, y: 0 },
    { value: 1, x: 0, y: 3 },
    { value: 7, x: 4, y: 3 },
    { value: 8, x: 1, y: 3 },
    { value: 0, x: 5, y: 3 },
  ],
  obstacles: [
    { x: 0, y: 1 },
    { x: 0, y: 0 },
  ],
};
