import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts. Do not edit by hand.
/** Scheduled 2026-09-08 (extra hard). 5×5, 5-digit code, intended 11-mirror solution (44% density), no ≤6-mirror shortcut. */
export const PUZZLE_079: Puzzle = {
  id: 79,
  code: "56579",
  gridSize: 5,
  source: { x: 2, y: 2, direction: "up" },
  flag: { x: 0, y: 3 },
  numbers: [
    { value: 5, x: 1, y: 0 },
    { value: 6, x: 0, y: 1 },
    { value: 5, x: 3, y: 3 },
    { value: 7, x: 4, y: 3 },
    { value: 9, x: 1, y: 3 },
  ],
  obstacles: [
    { x: 2, y: 3 },
    { x: 2, y: 4 },
  ],
};
