import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts — do not edit by hand.
/** Scheduled 2026-09-04 (extra hard). 7×7, 4-digit code, intended 17-mirror solution (35% density), no ≤3-mirror shortcut. */
export const PUZZLE_075: Puzzle = {
  id: 75,
  code: "5260",
  gridSize: 7,
  source: { x: 1, y: 3, direction: "down" },
  flag: { x: 2, y: 6 },
  numbers: [
    { value: 5, x: 1, y: 1 },
    { value: 2, x: 1, y: 2 },
    { value: 6, x: 4, y: 1 },
    { value: 0, x: 3, y: 3 },
  ],
  obstacles: [
    { x: 2, y: 4 },
    { x: 0, y: 5 },
    { x: 4, y: 4 },
  ],
};
