import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts, do not edit by hand.
/** Scheduled 2026-07-13 (extra hard). 8×8, 7-digit code, intended 27-mirror solution (42% density), no ≤3-mirror shortcut. */
export const PUZZLE_022: Puzzle = {
  id: 22,
  code: "2485634",
  gridSize: 8,
  source: { x: 0, y: 5, direction: "right" },
  flag: { x: 0, y: 4 },
  numbers: [
    { value: 2, x: 1, y: 4 },
    { value: 4, x: 2, y: 3 },
    { value: 8, x: 5, y: 2 },
    { value: 5, x: 4, y: 3 },
    { value: 6, x: 5, y: 6 },
    { value: 3, x: 7, y: 6 },
    { value: 4, x: 6, y: 7 },
  ],
  obstacles: [
    { x: 7, y: 3 },
    { x: 1, y: 2 },
    { x: 1, y: 6 },
    { x: 3, y: 6 },
  ],
};
