import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts. Do not edit by hand.
/** Scheduled 2026-09-12 (extra hard). 7×7, 4-digit code, intended 21-mirror solution (43% density), no ≤3-mirror shortcut. */
export const PUZZLE_083: Puzzle = {
  id: 83,
  code: "4209",
  gridSize: 7,
  source: { x: 2, y: 5, direction: "up" },
  flag: { x: 2, y: 6 },
  numbers: [
    { value: 4, x: 1, y: 3 },
    { value: 2, x: 5, y: 1 },
    { value: 0, x: 4, y: 2 },
    { value: 9, x: 1, y: 0 },
  ],
  obstacles: [
    { x: 6, y: 5 },
    { x: 1, y: 5 },
    { x: 1, y: 1 },
  ],
};
