import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts. Do not edit by hand.
/** Scheduled 2026-09-17 (extra hard). 5×5, 4-digit code, intended 11-mirror solution (44% density), no ≤6-mirror shortcut. */
export const PUZZLE_088: Puzzle = {
  id: 88,
  code: "3926",
  gridSize: 5,
  source: { x: 1, y: 3, direction: "up" },
  flag: { x: 3, y: 4 },
  numbers: [
    { value: 3, x: 0, y: 1 },
    { value: 9, x: 2, y: 2 },
    { value: 2, x: 1, y: 4 },
    { value: 6, x: 3, y: 3 },
  ],
  obstacles: [
    { x: 3, y: 2 },
    { x: 2, y: 0 },
  ],
};
