import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts — do not edit by hand.
/** Scheduled 2026-07-22 (extra hard). 8×8, 7-digit code, intended 25-mirror solution (39% density), no ≤3-mirror shortcut. */
export const PUZZLE_031: Puzzle = {
  id: 31,
  code: "5259355",
  gridSize: 8,
  source: { x: 7, y: 4, direction: "left" },
  flag: { x: 0, y: 5 },
  numbers: [
    { value: 5, x: 4, y: 5 },
    { value: 2, x: 3, y: 5 },
    { value: 5, x: 4, y: 3 },
    { value: 9, x: 5, y: 1 },
    { value: 3, x: 6, y: 6 },
    { value: 5, x: 1, y: 7 },
    { value: 5, x: 2, y: 5 },
  ],
  obstacles: [
    { x: 1, y: 5 },
    { x: 5, y: 5 },
    { x: 5, y: 0 },
    { x: 5, y: 7 },
  ],
};
