import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts, do not edit by hand.
/** Scheduled 2026-07-31 (extra hard). 8×8, 5-digit code, intended 26-mirror solution (41% density), no ≤3-mirror shortcut. */
export const PUZZLE_040: Puzzle = {
  id: 40,
  code: "53081",
  gridSize: 8,
  source: { x: 2, y: 7, direction: "up" },
  flag: { x: 7, y: 4 },
  numbers: [
    { value: 5, x: 4, y: 5 },
    { value: 3, x: 4, y: 6 },
    { value: 0, x: 1, y: 4 },
    { value: 8, x: 3, y: 0 },
    { value: 1, x: 6, y: 2 },
  ],
  obstacles: [
    { x: 7, y: 0 },
    { x: 3, y: 7 },
    { x: 1, y: 1 },
    { x: 6, y: 4 },
  ],
};
