import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts. Do not edit by hand.
/** Scheduled 2026-09-10 (extra hard). 8×8, 6-digit code, intended 24-mirror solution (38% density), no ≤3-mirror shortcut. */
export const PUZZLE_081: Puzzle = {
  id: 81,
  code: "209740",
  gridSize: 8,
  source: { x: 0, y: 6, direction: "right" },
  flag: { x: 0, y: 3 },
  numbers: [
    { value: 2, x: 4, y: 2 },
    { value: 0, x: 3, y: 0 },
    { value: 9, x: 2, y: 1 },
    { value: 7, x: 1, y: 7 },
    { value: 4, x: 5, y: 7 },
    { value: 0, x: 5, y: 5 },
  ],
  obstacles: [
    { x: 3, y: 1 },
    { x: 6, y: 5 },
    { x: 4, y: 5 },
    { x: 5, y: 1 },
  ],
};
