import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts — do not edit by hand.
/** Scheduled 2026-07-16 (extra hard). 6×6, 5-digit code, intended 16-mirror solution (44% density), no ≤4-mirror shortcut. */
export const PUZZLE_025: Puzzle = {
  id: 25,
  code: "85574",
  gridSize: 6,
  source: { x: 3, y: 0, direction: "down" },
  flag: { x: 5, y: 3 },
  numbers: [
    { value: 8, x: 4, y: 1 },
    { value: 5, x: 4, y: 0 },
    { value: 5, x: 0, y: 3 },
    { value: 7, x: 1, y: 5 },
    { value: 4, x: 5, y: 4 },
  ],
  obstacles: [
    { x: 0, y: 0 },
    { x: 0, y: 1 },
  ],
};
