import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts, do not edit by hand.
/** Scheduled 2026-07-24 (extra hard). 8×8, 6-digit code, intended 21-mirror solution (33% density), no ≤3-mirror shortcut. */
export const PUZZLE_033: Puzzle = {
  id: 33,
  code: "562325",
  gridSize: 8,
  source: { x: 3, y: 7, direction: "up" },
  flag: { x: 0, y: 5 },
  numbers: [
    { value: 5, x: 4, y: 4 },
    { value: 6, x: 5, y: 4 },
    { value: 2, x: 7, y: 5 },
    { value: 3, x: 5, y: 6 },
    { value: 2, x: 4, y: 7 },
    { value: 5, x: 1, y: 5 },
  ],
  obstacles: [
    { x: 7, y: 2 },
    { x: 7, y: 7 },
    { x: 4, y: 1 },
    { x: 6, y: 4 },
  ],
};
