import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts. Do not edit by hand.
/** Scheduled 2026-09-14 (extra hard). 7×7, 5-digit code, intended 20-mirror solution (41% density), no ≤3-mirror shortcut. */
export const PUZZLE_085: Puzzle = {
  id: 85,
  code: "85771",
  gridSize: 7,
  source: { x: 0, y: 3, direction: "right" },
  flag: { x: 3, y: 4 },
  numbers: [
    { value: 8, x: 1, y: 1 },
    { value: 5, x: 2, y: 2 },
    { value: 7, x: 1, y: 5 },
    { value: 7, x: 0, y: 5 },
    { value: 1, x: 2, y: 4 },
  ],
  obstacles: [
    { x: 3, y: 5 },
    { x: 1, y: 0 },
    { x: 4, y: 6 },
  ],
};
