import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts, do not edit by hand.
/** Scheduled 2026-07-30 (extra hard). 8×8, 5-digit code, intended 26-mirror solution (41% density), no ≤3-mirror shortcut. */
export const PUZZLE_039: Puzzle = {
  id: 39,
  code: "18504",
  gridSize: 8,
  source: { x: 7, y: 2, direction: "left" },
  flag: { x: 7, y: 5 },
  numbers: [
    { value: 1, x: 5, y: 0 },
    { value: 8, x: 6, y: 1 },
    { value: 5, x: 3, y: 3 },
    { value: 0, x: 6, y: 5 },
    { value: 4, x: 7, y: 4 },
  ],
  obstacles: [
    { x: 5, y: 4 },
    { x: 1, y: 7 },
    { x: 7, y: 1 },
    { x: 4, y: 3 },
  ],
};
