import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts. Do not edit by hand.
/** Scheduled 2026-09-15 (extra hard). 5×5, 5-digit code, intended 13-mirror solution (52% density), no ≤5-mirror shortcut. */
export const PUZZLE_086: Puzzle = {
  id: 86,
  code: "91822",
  gridSize: 5,
  source: { x: 3, y: 1, direction: "up" },
  flag: { x: 4, y: 2 },
  numbers: [
    { value: 9, x: 2, y: 3 },
    { value: 1, x: 1, y: 2 },
    { value: 8, x: 1, y: 0 },
    { value: 2, x: 0, y: 1 },
    { value: 2, x: 1, y: 4 },
  ],
  obstacles: [],
};
