import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts. Do not edit by hand.
/** Scheduled 2026-08-19 (extra hard). 7×7, 5-digit code, intended 21-mirror solution (43% density), no ≤3-mirror shortcut. */
export const PUZZLE_059: Puzzle = {
  id: 59,
  code: "57334",
  gridSize: 7,
  source: { x: 5, y: 4, direction: "left" },
  flag: { x: 6, y: 2 },
  numbers: [
    { value: 5, x: 3, y: 1 },
    { value: 7, x: 2, y: 2 },
    { value: 3, x: 3, y: 6 },
    { value: 3, x: 0, y: 1 },
    { value: 4, x: 1, y: 0 },
  ],
  obstacles: [
    { x: 0, y: 4 },
    { x: 1, y: 1 },
    { x: 1, y: 6 },
  ],
};
