import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts. Do not edit by hand.
/** Scheduled 2026-08-27 (extra hard). 5×5, 5-digit code, intended 12-mirror solution (48% density), no ≤6-mirror shortcut. */
export const PUZZLE_067: Puzzle = {
  id: 67,
  code: "32685",
  gridSize: 5,
  source: { x: 1, y: 4, direction: "up" },
  flag: { x: 4, y: 2 },
  numbers: [
    { value: 3, x: 2, y: 4 },
    { value: 2, x: 2, y: 3 },
    { value: 6, x: 2, y: 1 },
    { value: 8, x: 3, y: 0 },
    { value: 5, x: 4, y: 1 },
  ],
  obstacles: [
    { x: 3, y: 2 },
    { x: 3, y: 1 },
  ],
};
