import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts — do not edit by hand.
/** Scheduled 2026-07-26 (extra hard). 7×7, 5-digit code, intended 18-mirror solution (37% density), no ≤3-mirror shortcut. */
export const PUZZLE_035: Puzzle = {
  id: 35,
  code: "72257",
  gridSize: 7,
  source: { x: 3, y: 1, direction: "right" },
  flag: { x: 4, y: 5 },
  numbers: [
    { value: 7, x: 3, y: 3 },
    { value: 2, x: 4, y: 6 },
    { value: 2, x: 6, y: 5 },
    { value: 5, x: 4, y: 3 },
    { value: 7, x: 2, y: 4 },
  ],
  obstacles: [
    { x: 2, y: 6 },
    { x: 2, y: 0 },
    { x: 0, y: 4 },
  ],
};
