import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts, do not edit by hand.
/** Scheduled 2026-08-01 (extra hard). 7×7, 5-digit code, intended 20-mirror solution (41% density), no ≤3-mirror shortcut. */
export const PUZZLE_041: Puzzle = {
  id: 41,
  code: "32465",
  gridSize: 7,
  source: { x: 5, y: 4, direction: "down" },
  flag: { x: 2, y: 0 },
  numbers: [
    { value: 3, x: 4, y: 5 },
    { value: 2, x: 2, y: 3 },
    { value: 4, x: 5, y: 2 },
    { value: 6, x: 1, y: 3 },
    { value: 5, x: 0, y: 4 },
  ],
  obstacles: [
    { x: 5, y: 1 },
    { x: 6, y: 4 },
    { x: 1, y: 6 },
  ],
};
