import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts, do not edit by hand.
/** Scheduled 2026-07-26 (extra hard). 6×6, 4-digit code, intended 15-mirror solution (42% density), no ≤4-mirror shortcut. */
export const PUZZLE_035: Puzzle = {
  id: 35,
  code: "2638",
  gridSize: 6,
  source: { x: 4, y: 2, direction: "up" },
  flag: { x: 2, y: 5 },
  numbers: [
    { value: 2, x: 3, y: 1 },
    { value: 6, x: 4, y: 3 },
    { value: 3, x: 3, y: 4 },
    { value: 8, x: 1, y: 2 },
  ],
  obstacles: [
    { x: 1, y: 3 },
    { x: 4, y: 0 },
  ],
};
