import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts — do not edit by hand.
/** Scheduled 2026-07-19 (extra hard). 5×5, 4-digit code, intended 11-mirror solution (44% density), no ≤6-mirror shortcut. */
export const PUZZLE_028: Puzzle = {
  id: 28,
  code: "5885",
  gridSize: 5,
  source: { x: 2, y: 2, direction: "right" },
  flag: { x: 0, y: 3 },
  numbers: [
    { value: 5, x: 3, y: 1 },
    { value: 8, x: 2, y: 0 },
    { value: 8, x: 2, y: 3 },
    { value: 5, x: 1, y: 4 },
  ],
  obstacles: [
    { x: 4, y: 4 },
    { x: 3, y: 4 },
  ],
};
