import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts. Do not edit by hand.
/** Scheduled 2026-09-18 (extra hard). 8×8, 4-digit code, intended 25-mirror solution (39% density), no ≤3-mirror shortcut. */
export const PUZZLE_089: Puzzle = {
  id: 89,
  code: "8793",
  gridSize: 8,
  source: { x: 4, y: 0, direction: "down" },
  flag: { x: 1, y: 6 },
  numbers: [
    { value: 8, x: 3, y: 0 },
    { value: 7, x: 3, y: 1 },
    { value: 9, x: 6, y: 5 },
    { value: 3, x: 6, y: 4 },
  ],
  obstacles: [
    { x: 6, y: 6 },
    { x: 0, y: 4 },
    { x: 1, y: 0 },
    { x: 5, y: 7 },
  ],
};
