import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts. Do not edit by hand.
/** Scheduled 2026-09-09 (extra hard). 7×7, 5-digit code, intended 20-mirror solution (41% density), no ≤3-mirror shortcut. */
export const PUZZLE_080: Puzzle = {
  id: 80,
  code: "15488",
  gridSize: 7,
  source: { x: 3, y: 0, direction: "down" },
  flag: { x: 2, y: 6 },
  numbers: [
    { value: 1, x: 5, y: 1 },
    { value: 5, x: 6, y: 4 },
    { value: 4, x: 4, y: 6 },
    { value: 8, x: 1, y: 2 },
    { value: 8, x: 0, y: 3 },
  ],
  obstacles: [
    { x: 1, y: 3 },
    { x: 3, y: 3 },
    { x: 6, y: 2 },
  ],
};
