import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts. Do not edit by hand.
/** Scheduled 2026-08-17 (extra hard). 8×8, 6-digit code, intended 23-mirror solution (36% density), no ≤3-mirror shortcut. */
export const PUZZLE_057: Puzzle = {
  id: 57,
  code: "543399",
  gridSize: 8,
  source: { x: 4, y: 0, direction: "down" },
  flag: { x: 1, y: 5 },
  numbers: [
    { value: 5, x: 7, y: 2 },
    { value: 4, x: 6, y: 1 },
    { value: 3, x: 3, y: 6 },
    { value: 3, x: 2, y: 5 },
    { value: 9, x: 2, y: 3 },
    { value: 9, x: 1, y: 4 },
  ],
  obstacles: [
    { x: 5, y: 0 },
    { x: 6, y: 0 },
    { x: 2, y: 2 },
    { x: 3, y: 1 },
  ],
};
