import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts. Do not edit by hand.
/** Scheduled 2026-09-13 (extra hard). 8×8, 5-digit code, intended 26-mirror solution (41% density), no ≤3-mirror shortcut. */
export const PUZZLE_084: Puzzle = {
  id: 84,
  code: "97505",
  gridSize: 8,
  source: { x: 1, y: 4, direction: "right" },
  flag: { x: 6, y: 0 },
  numbers: [
    { value: 9, x: 1, y: 2 },
    { value: 7, x: 1, y: 3 },
    { value: 5, x: 7, y: 3 },
    { value: 0, x: 6, y: 2 },
    { value: 5, x: 4, y: 1 },
  ],
  obstacles: [
    { x: 1, y: 1 },
    { x: 2, y: 7 },
    { x: 6, y: 5 },
    { x: 6, y: 3 },
  ],
};
