import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts, do not edit by hand.
/** Scheduled 2026-07-17 (extra hard). 5×5, 4-digit code, intended 11-mirror solution (44% density), no ≤6-mirror shortcut. */
export const PUZZLE_026: Puzzle = {
  id: 26,
  code: "7295",
  gridSize: 5,
  source: { x: 1, y: 3, direction: "left" },
  flag: { x: 4, y: 3 },
  numbers: [
    { value: 7, x: 1, y: 2 },
    { value: 2, x: 2, y: 1 },
    { value: 9, x: 3, y: 2 },
    { value: 5, x: 2, y: 3 },
  ],
  obstacles: [
    { x: 3, y: 0 },
    { x: 2, y: 0 },
  ],
};
