import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts — do not edit by hand.
/** Scheduled 2026-08-14 (extra hard). 7×7, 6-digit code, intended 20-mirror solution (41% density), no ≤3-mirror shortcut. */
export const PUZZLE_054: Puzzle = {
  id: 54,
  code: "857268",
  gridSize: 7,
  source: { x: 0, y: 2, direction: "right" },
  flag: { x: 2, y: 5 },
  numbers: [
    { value: 8, x: 2, y: 3 },
    { value: 5, x: 2, y: 1 },
    { value: 7, x: 4, y: 3 },
    { value: 2, x: 3, y: 5 },
    { value: 6, x: 2, y: 6 },
    { value: 8, x: 1, y: 5 },
  ],
  obstacles: [
    { x: 6, y: 4 },
    { x: 2, y: 4 },
    { x: 0, y: 1 },
  ],
};
