import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts, do not edit by hand.
/** Scheduled 2026-07-29 (extra hard). 7×7, 6-digit code, intended 20-mirror solution (41% density), no ≤3-mirror shortcut. */
export const PUZZLE_038: Puzzle = {
  id: 38,
  code: "453907",
  gridSize: 7,
  source: { x: 0, y: 1, direction: "right" },
  flag: { x: 6, y: 1 },
  numbers: [
    { value: 4, x: 2, y: 3 },
    { value: 5, x: 1, y: 3 },
    { value: 3, x: 4, y: 3 },
    { value: 9, x: 3, y: 5 },
    { value: 0, x: 2, y: 5 },
    { value: 7, x: 3, y: 3 },
  ],
  obstacles: [
    { x: 5, y: 4 },
    { x: 1, y: 5 },
    { x: 0, y: 3 },
  ],
};
