import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts — do not edit by hand.
/** Scheduled 2026-07-27 (extra hard). 6×6, 5-digit code, intended 15-mirror solution (42% density), no ≤4-mirror shortcut. */
export const PUZZLE_036: Puzzle = {
  id: 36,
  code: "78731",
  gridSize: 6,
  source: { x: 4, y: 2, direction: "left" },
  flag: { x: 5, y: 4 },
  numbers: [
    { value: 7, x: 2, y: 3 },
    { value: 8, x: 1, y: 3 },
    { value: 7, x: 5, y: 2 },
    { value: 3, x: 3, y: 3 },
    { value: 1, x: 4, y: 5 },
  ],
  obstacles: [
    { x: 0, y: 3 },
    { x: 4, y: 4 },
  ],
};
