import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts — do not edit by hand.
/** Scheduled 2026-07-21 (extra hard). 5×5, 5-digit code, intended 12-mirror solution (48% density), no ≤6-mirror shortcut. */
export const PUZZLE_030: Puzzle = {
  id: 30,
  code: "10228",
  gridSize: 5,
  source: { x: 2, y: 2, direction: "left" },
  flag: { x: 4, y: 2 },
  numbers: [
    { value: 1, x: 2, y: 3 },
    { value: 0, x: 3, y: 2 },
    { value: 2, x: 1, y: 0 },
    { value: 2, x: 0, y: 1 },
    { value: 8, x: 1, y: 4 },
  ],
  obstacles: [
    { x: 1, y: 1 },
  ],
};
