import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts — do not edit by hand.
/** Scheduled 2026-07-20 (extra hard). 8×8, 5-digit code, intended 27-mirror solution (42% density), no ≤3-mirror shortcut. */
export const PUZZLE_029: Puzzle = {
  id: 29,
  code: "19178",
  gridSize: 8,
  source: { x: 4, y: 2, direction: "down" },
  flag: { x: 5, y: 0 },
  numbers: [
    { value: 1, x: 2, y: 3 },
    { value: 9, x: 1, y: 4 },
    { value: 1, x: 1, y: 6 },
    { value: 7, x: 5, y: 7 },
    { value: 8, x: 7, y: 3 },
  ],
  obstacles: [
    { x: 2, y: 7 },
    { x: 7, y: 7 },
    { x: 3, y: 6 },
    { x: 5, y: 1 },
  ],
};
