import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts — do not edit by hand.
/** Scheduled 2026-07-18 (extra hard). 8×8, 6-digit code, intended 20-mirror solution (31% density), no ≤3-mirror shortcut. */
export const PUZZLE_027: Puzzle = {
  id: 27,
  code: "312223",
  gridSize: 8,
  source: { x: 6, y: 0, direction: "down" },
  flag: { x: 1, y: 1 },
  numbers: [
    { value: 3, x: 7, y: 2 },
    { value: 1, x: 5, y: 3 },
    { value: 2, x: 2, y: 3 },
    { value: 2, x: 2, y: 5 },
    { value: 2, x: 2, y: 4 },
    { value: 3, x: 2, y: 2 },
  ],
  obstacles: [
    { x: 4, y: 6 },
    { x: 2, y: 0 },
    { x: 1, y: 7 },
    { x: 6, y: 2 },
  ],
};
