import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts, do not edit by hand.
/** Scheduled 2026-07-22 (extra hard). 7×7, 6-digit code, intended 20-mirror solution (41% density), no ≤3-mirror shortcut. */
export const PUZZLE_031: Puzzle = {
  id: 31,
  code: "959559",
  gridSize: 7,
  source: { x: 3, y: 4, direction: "down" },
  flag: { x: 0, y: 4 },
  numbers: [
    { value: 9, x: 5, y: 6 },
    { value: 5, x: 5, y: 5 },
    { value: 9, x: 2, y: 1 },
    { value: 5, x: 3, y: 2 },
    { value: 5, x: 2, y: 6 },
    { value: 9, x: 0, y: 5 },
  ],
  obstacles: [
    { x: 4, y: 1 },
    { x: 5, y: 0 },
    { x: 6, y: 0 },
  ],
};
