import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts — do not edit by hand.
/** Scheduled 2026-08-22 (extra hard). 5×5, 5-digit code, intended 11-mirror solution (44% density), no ≤6-mirror shortcut. */
export const PUZZLE_062: Puzzle = {
  id: 62,
  code: "72651",
  gridSize: 5,
  source: { x: 1, y: 3, direction: "right" },
  flag: { x: 2, y: 0 },
  numbers: [
    { value: 7, x: 2, y: 2 },
    { value: 2, x: 0, y: 1 },
    { value: 6, x: 2, y: 1 },
    { value: 5, x: 4, y: 1 },
    { value: 1, x: 3, y: 0 },
  ],
  obstacles: [
    { x: 4, y: 3 },
    { x: 1, y: 4 },
  ],
};
