import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts. Do not edit by hand.
/** Scheduled 2026-09-23 (extra hard). 8×8, 6-digit code, intended 26-mirror solution (41% density), no ≤3-mirror shortcut. */
export const PUZZLE_094: Puzzle = {
  id: 94,
  code: "739379",
  gridSize: 8,
  source: { x: 1, y: 6, direction: "right" },
  flag: { x: 2, y: 0 },
  numbers: [
    { value: 7, x: 1, y: 5 },
    { value: 3, x: 2, y: 4 },
    { value: 9, x: 5, y: 5 },
    { value: 3, x: 6, y: 5 },
    { value: 7, x: 1, y: 2 },
    { value: 9, x: 0, y: 1 },
  ],
  obstacles: [
    { x: 1, y: 3 },
    { x: 7, y: 3 },
    { x: 5, y: 7 },
    { x: 0, y: 5 },
  ],
};
