import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts — do not edit by hand.
/** Scheduled 2026-07-20 (extra hard). 7×7, 5-digit code, intended 21-mirror solution (43% density), no ≤3-mirror shortcut. */
export const PUZZLE_029: Puzzle = {
  id: 29,
  code: "31786",
  gridSize: 7,
  source: { x: 1, y: 4, direction: "right" },
  flag: { x: 2, y: 0 },
  numbers: [
    { value: 3, x: 4, y: 1 },
    { value: 1, x: 5, y: 1 },
    { value: 7, x: 4, y: 5 },
    { value: 8, x: 2, y: 6 },
    { value: 6, x: 0, y: 5 },
  ],
  obstacles: [
    { x: 4, y: 6 },
    { x: 6, y: 6 },
    { x: 6, y: 5 },
  ],
};
