import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts. Do not edit by hand.
/** Scheduled 2026-08-24 (extra hard). 7×7, 6-digit code, intended 20-mirror solution (41% density), no ≤3-mirror shortcut. */
export const PUZZLE_064: Puzzle = {
  id: 64,
  code: "404385",
  gridSize: 7,
  source: { x: 5, y: 0, direction: "down" },
  flag: { x: 0, y: 4 },
  numbers: [
    { value: 4, x: 4, y: 0 },
    { value: 0, x: 4, y: 1 },
    { value: 4, x: 4, y: 2 },
    { value: 3, x: 0, y: 1 },
    { value: 8, x: 3, y: 5 },
    { value: 5, x: 2, y: 6 },
  ],
  obstacles: [
    { x: 2, y: 0 },
    { x: 1, y: 5 },
    { x: 5, y: 3 },
  ],
};
