import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts. Do not edit by hand.
/** Scheduled 2026-09-03 (extra hard). 7×7, 6-digit code, intended 20-mirror solution (41% density), no ≤3-mirror shortcut. */
export const PUZZLE_074: Puzzle = {
  id: 74,
  code: "615018",
  gridSize: 7,
  source: { x: 1, y: 1, direction: "up" },
  flag: { x: 6, y: 2 },
  numbers: [
    { value: 6, x: 6, y: 4 },
    { value: 1, x: 5, y: 3 },
    { value: 5, x: 4, y: 6 },
    { value: 0, x: 3, y: 5 },
    { value: 1, x: 3, y: 1 },
    { value: 8, x: 4, y: 0 },
  ],
  obstacles: [
    { x: 2, y: 0 },
    { x: 1, y: 4 },
    { x: 2, y: 5 },
  ],
};
