import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts — do not edit by hand.
/** Scheduled 2026-08-20 (extra hard). 8×8, 5-digit code, intended 26-mirror solution (41% density), no ≤3-mirror shortcut. */
export const PUZZLE_060: Puzzle = {
  id: 60,
  code: "63379",
  gridSize: 8,
  source: { x: 0, y: 3, direction: "right" },
  flag: { x: 5, y: 7 },
  numbers: [
    { value: 6, x: 1, y: 1 },
    { value: 3, x: 1, y: 0 },
    { value: 3, x: 4, y: 5 },
    { value: 7, x: 5, y: 4 },
    { value: 9, x: 4, y: 6 },
  ],
  obstacles: [
    { x: 3, y: 0 },
    { x: 0, y: 4 },
    { x: 0, y: 2 },
    { x: 4, y: 1 },
  ],
};
