import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts — do not edit by hand.
/** Scheduled 2026-08-31 (extra hard). 8×8, 5-digit code, intended 22-mirror solution (34% density), no ≤3-mirror shortcut. */
export const PUZZLE_071: Puzzle = {
  id: 71,
  code: "35060",
  gridSize: 8,
  source: { x: 3, y: 2, direction: "up" },
  flag: { x: 2, y: 5 },
  numbers: [
    { value: 3, x: 6, y: 2 },
    { value: 5, x: 6, y: 3 },
    { value: 0, x: 2, y: 1 },
    { value: 6, x: 3, y: 3 },
    { value: 0, x: 2, y: 4 },
  ],
  obstacles: [
    { x: 0, y: 5 },
    { x: 1, y: 4 },
    { x: 4, y: 5 },
    { x: 6, y: 1 },
  ],
};
