import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts — do not edit by hand.
/** Scheduled 2026-09-02 (extra hard). 8×8, 6-digit code, intended 27-mirror solution (42% density), no ≤3-mirror shortcut. */
export const PUZZLE_073: Puzzle = {
  id: 73,
  code: "747113",
  gridSize: 8,
  source: { x: 4, y: 7, direction: "up" },
  flag: { x: 7, y: 2 },
  numbers: [
    { value: 7, x: 5, y: 2 },
    { value: 4, x: 1, y: 6 },
    { value: 7, x: 3, y: 3 },
    { value: 1, x: 2, y: 3 },
    { value: 1, x: 0, y: 3 },
    { value: 3, x: 1, y: 0 },
  ],
  obstacles: [
    { x: 1, y: 2 },
    { x: 6, y: 1 },
    { x: 5, y: 1 },
    { x: 0, y: 7 },
  ],
};
