import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts. Do not edit by hand.
/** Scheduled 2026-09-20 (extra hard). 8×8, 5-digit code, intended 26-mirror solution (41% density), no ≤3-mirror shortcut. */
export const PUZZLE_091: Puzzle = {
  id: 91,
  code: "47262",
  gridSize: 8,
  source: { x: 7, y: 6, direction: "left" },
  flag: { x: 7, y: 5 },
  numbers: [
    { value: 4, x: 4, y: 7 },
    { value: 7, x: 4, y: 5 },
    { value: 2, x: 3, y: 3 },
    { value: 6, x: 7, y: 1 },
    { value: 2, x: 6, y: 0 },
  ],
  obstacles: [
    { x: 1, y: 3 },
    { x: 2, y: 7 },
    { x: 1, y: 6 },
    { x: 4, y: 4 },
  ],
};
