import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts. Do not edit by hand.
/** Scheduled 2026-09-11 (extra hard). 7×7, 6-digit code, intended 18-mirror solution (37% density), no ≤3-mirror shortcut. */
export const PUZZLE_082: Puzzle = {
  id: 82,
  code: "994901",
  gridSize: 7,
  source: { x: 4, y: 0, direction: "down" },
  flag: { x: 3, y: 1 },
  numbers: [
    { value: 9, x: 5, y: 2 },
    { value: 9, x: 1, y: 3 },
    { value: 4, x: 2, y: 4 },
    { value: 9, x: 6, y: 2 },
    { value: 0, x: 3, y: 0 },
    { value: 1, x: 2, y: 1 },
  ],
  obstacles: [
    { x: 6, y: 4 },
    { x: 1, y: 1 },
    { x: 6, y: 0 },
  ],
};
