import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts. Do not edit by hand.
/** Scheduled 2026-08-25 (extra hard). 5×5, 4-digit code, intended 12-mirror solution (48% density), no ≤6-mirror shortcut. */
export const PUZZLE_065: Puzzle = {
  id: 65,
  code: "6539",
  gridSize: 5,
  source: { x: 0, y: 2, direction: "right" },
  flag: { x: 4, y: 2 },
  numbers: [
    { value: 6, x: 2, y: 4 },
    { value: 5, x: 2, y: 3 },
    { value: 3, x: 2, y: 0 },
    { value: 9, x: 4, y: 1 },
  ],
  obstacles: [
    { x: 3, y: 2 },
    { x: 0, y: 0 },
  ],
};
