import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts, do not edit by hand.
/** Scheduled 2026-07-23 (extra hard). 6×6, 6-digit code, intended 15-mirror solution (42% density), no ≤4-mirror shortcut. */
export const PUZZLE_032: Puzzle = {
  id: 32,
  code: "239194",
  gridSize: 6,
  source: { x: 0, y: 1, direction: "right" },
  flag: { x: 4, y: 5 },
  numbers: [
    { value: 2, x: 1, y: 3 },
    { value: 3, x: 1, y: 2 },
    { value: 9, x: 4, y: 3 },
    { value: 1, x: 5, y: 3 },
    { value: 9, x: 2, y: 4 },
    { value: 4, x: 3, y: 5 },
  ],
  obstacles: [
    { x: 4, y: 0 },
    { x: 1, y: 0 },
  ],
};
