import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts, do not edit by hand.
/** Scheduled 2026-08-02 (extra hard). 6×6, 5-digit code, intended 15-mirror solution (42% density), no ≤4-mirror shortcut. */
export const PUZZLE_042: Puzzle = {
  id: 42,
  code: "78973",
  gridSize: 6,
  source: { x: 1, y: 2, direction: "right" },
  flag: { x: 4, y: 0 },
  numbers: [
    { value: 7, x: 4, y: 4 },
    { value: 8, x: 5, y: 3 },
    { value: 9, x: 1, y: 4 },
    { value: 7, x: 1, y: 3 },
    { value: 3, x: 2, y: 1 },
  ],
  obstacles: [
    { x: 5, y: 5 },
    { x: 1, y: 1 },
  ],
};
