import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts, do not edit by hand.
/** Scheduled 2026-08-11 (extra hard). 7×7, 5-digit code, intended 19-mirror solution (39% density), no ≤3-mirror shortcut. */
export const PUZZLE_051: Puzzle = {
  id: 51,
  code: "73574",
  gridSize: 7,
  source: { x: 0, y: 3, direction: "right" },
  flag: { x: 3, y: 6 },
  numbers: [
    { value: 7, x: 0, y: 5 },
    { value: 3, x: 1, y: 6 },
    { value: 5, x: 1, y: 2 },
    { value: 7, x: 3, y: 5 },
    { value: 4, x: 5, y: 4 },
  ],
  obstacles: [
    { x: 6, y: 6 },
    { x: 3, y: 1 },
    { x: 5, y: 6 },
  ],
};
