import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts — do not edit by hand.
/** Scheduled 2026-07-20 (extra hard). 7×7, 5-digit code, intended 20-mirror solution (41% density), no ≤3-mirror shortcut. */
export const PUZZLE_029: Puzzle = {
  id: 29,
  code: "93480",
  gridSize: 7,
  source: { x: 6, y: 5, direction: "left" },
  flag: { x: 3, y: 5 },
  numbers: [
    { value: 9, x: 3, y: 3 },
    { value: 3, x: 3, y: 1 },
    { value: 4, x: 4, y: 0 },
    { value: 8, x: 4, y: 2 },
    { value: 0, x: 3, y: 4 },
  ],
  obstacles: [
    { x: 1, y: 1 },
    { x: 2, y: 1 },
    { x: 3, y: 6 },
  ],
};
