import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts, do not edit by hand.
/** Scheduled 2026-07-28 (extra hard). 8×8, 5-digit code, intended 24-mirror solution (38% density), no ≤3-mirror shortcut. */
export const PUZZLE_037: Puzzle = {
  id: 37,
  code: "27839",
  gridSize: 8,
  source: { x: 5, y: 6, direction: "up" },
  flag: { x: 6, y: 4 },
  numbers: [
    { value: 2, x: 6, y: 0 },
    { value: 7, x: 2, y: 3 },
    { value: 8, x: 6, y: 5 },
    { value: 3, x: 7, y: 4 },
    { value: 9, x: 6, y: 3 },
  ],
  obstacles: [
    { x: 4, y: 7 },
    { x: 6, y: 6 },
    { x: 3, y: 0 },
    { x: 7, y: 2 },
  ],
};
