import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts — do not edit by hand.
/** Scheduled 2026-07-22 (extra hard). 8×8, 7-digit code, intended 22-mirror solution (34% density), no ≤3-mirror shortcut. */
export const PUZZLE_031: Puzzle = {
  id: 31,
  code: "2469769",
  gridSize: 8,
  source: { x: 0, y: 2, direction: "right" },
  flag: { x: 7, y: 4 },
  numbers: [
    { value: 2, x: 1, y: 3 },
    { value: 4, x: 0, y: 5 },
    { value: 6, x: 1, y: 5 },
    { value: 9, x: 4, y: 4 },
    { value: 7, x: 3, y: 3 },
    { value: 6, x: 6, y: 3 },
    { value: 9, x: 7, y: 3 },
  ],
  obstacles: [
    { x: 0, y: 1 },
    { x: 6, y: 6 },
    { x: 7, y: 0 },
    { x: 7, y: 1 },
  ],
};
