import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts. Do not edit by hand.
/** Scheduled 2026-09-16 (extra hard). 7×7, 4-digit code, intended 19-mirror solution (39% density), no ≤3-mirror shortcut. */
export const PUZZLE_087: Puzzle = {
  id: 87,
  code: "8972",
  gridSize: 7,
  source: { x: 6, y: 2, direction: "left" },
  flag: { x: 5, y: 0 },
  numbers: [
    { value: 8, x: 6, y: 4 },
    { value: 9, x: 4, y: 3 },
    { value: 7, x: 3, y: 6 },
    { value: 2, x: 3, y: 1 },
  ],
  obstacles: [
    { x: 0, y: 3 },
    { x: 0, y: 2 },
    { x: 5, y: 1 },
  ],
};
