import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts — do not edit by hand.
/** Scheduled 2026-08-12 (extra hard). 8×8, 6-digit code, intended 24-mirror solution (38% density), no ≤3-mirror shortcut. */
export const PUZZLE_052: Puzzle = {
  id: 52,
  code: "456333",
  gridSize: 8,
  source: { x: 2, y: 3, direction: "left" },
  flag: { x: 3, y: 0 },
  numbers: [
    { value: 4, x: 4, y: 5 },
    { value: 5, x: 3, y: 7 },
    { value: 6, x: 2, y: 5 },
    { value: 3, x: 3, y: 6 },
    { value: 3, x: 3, y: 4 },
    { value: 3, x: 3, y: 1 },
  ],
  obstacles: [
    { x: 6, y: 5 },
    { x: 0, y: 4 },
    { x: 0, y: 0 },
    { x: 1, y: 7 },
  ],
};
