import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts. Do not edit by hand.
/** Scheduled 2026-09-06 (extra hard). 6×6, 4-digit code, intended 15-mirror solution (42% density), no ≤4-mirror shortcut. */
export const PUZZLE_077: Puzzle = {
  id: 77,
  code: "2190",
  gridSize: 6,
  source: { x: 1, y: 3, direction: "right" },
  flag: { x: 5, y: 1 },
  numbers: [
    { value: 2, x: 1, y: 1 },
    { value: 1, x: 0, y: 1 },
    { value: 9, x: 1, y: 4 },
    { value: 0, x: 2, y: 4 },
  ],
  obstacles: [
    { x: 0, y: 3 },
    { x: 5, y: 4 },
  ],
};
