import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts — do not edit by hand.
/** Scheduled 2026-07-24 (extra hard). 7×7, 6-digit code, intended 21-mirror solution (43% density), no ≤3-mirror shortcut. */
export const PUZZLE_033: Puzzle = {
  id: 33,
  code: "905603",
  gridSize: 7,
  source: { x: 5, y: 2, direction: "left" },
  flag: { x: 4, y: 6 },
  numbers: [
    { value: 9, x: 1, y: 6 },
    { value: 0, x: 2, y: 5 },
    { value: 5, x: 0, y: 1 },
    { value: 6, x: 2, y: 1 },
    { value: 0, x: 3, y: 0 },
    { value: 3, x: 6, y: 1 },
  ],
  obstacles: [
    { x: 5, y: 1 },
    { x: 3, y: 5 },
    { x: 5, y: 3 },
  ],
};
