import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts. Do not edit by hand.
/** Scheduled 2026-09-24 (extra hard). 6×6, 6-digit code, intended 16-mirror solution (44% density), no ≤4-mirror shortcut. */
export const PUZZLE_095: Puzzle = {
  id: 95,
  code: "299865",
  gridSize: 6,
  source: { x: 3, y: 4, direction: "up" },
  flag: { x: 3, y: 0 },
  numbers: [
    { value: 2, x: 1, y: 0 },
    { value: 9, x: 2, y: 1 },
    { value: 9, x: 1, y: 3 },
    { value: 8, x: 0, y: 4 },
    { value: 6, x: 1, y: 5 },
    { value: 5, x: 5, y: 4 },
  ],
  obstacles: [
    { x: 4, y: 1 },
    { x: 1, y: 4 },
  ],
};
