import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts — do not edit by hand.
/** Scheduled 2026-09-05 (extra hard). 8×8, 6-digit code, intended 25-mirror solution (39% density), no ≤3-mirror shortcut. */
export const PUZZLE_076: Puzzle = {
  id: 76,
  code: "943725",
  gridSize: 8,
  source: { x: 0, y: 4, direction: "right" },
  flag: { x: 2, y: 6 },
  numbers: [
    { value: 9, x: 4, y: 3 },
    { value: 4, x: 5, y: 2 },
    { value: 3, x: 6, y: 3 },
    { value: 7, x: 2, y: 2 },
    { value: 2, x: 1, y: 2 },
    { value: 5, x: 3, y: 6 },
  ],
  obstacles: [
    { x: 4, y: 1 },
    { x: 0, y: 6 },
    { x: 3, y: 1 },
    { x: 7, y: 0 },
  ],
};
