import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts. Do not edit by hand.
/** Scheduled 2026-08-16 (extra hard). 7×7, 5-digit code, intended 19-mirror solution (39% density), no ≤3-mirror shortcut. */
export const PUZZLE_056: Puzzle = {
  id: 56,
  code: "63048",
  gridSize: 7,
  source: { x: 6, y: 4, direction: "left" },
  flag: { x: 0, y: 2 },
  numbers: [
    { value: 6, x: 5, y: 3 },
    { value: 3, x: 2, y: 5 },
    { value: 0, x: 2, y: 6 },
    { value: 4, x: 1, y: 0 },
    { value: 8, x: 2, y: 1 },
  ],
  obstacles: [
    { x: 5, y: 1 },
    { x: 6, y: 2 },
    { x: 4, y: 1 },
  ],
};
