import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts — do not edit by hand.
/** Scheduled 2026-08-13 (extra hard). 6×6, 5-digit code, intended 14-mirror solution (39% density), no ≤4-mirror shortcut. */
export const PUZZLE_053: Puzzle = {
  id: 53,
  code: "90722",
  gridSize: 6,
  source: { x: 0, y: 3, direction: "right" },
  flag: { x: 5, y: 3 },
  numbers: [
    { value: 9, x: 4, y: 1 },
    { value: 0, x: 4, y: 0 },
    { value: 7, x: 2, y: 4 },
    { value: 2, x: 3, y: 4 },
    { value: 2, x: 4, y: 4 },
  ],
  obstacles: [
    { x: 1, y: 1 },
    { x: 0, y: 2 },
  ],
};
