import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts — do not edit by hand.
/** Scheduled 2026-08-04 (extra hard). 6×6, 5-digit code, intended 16-mirror solution (44% density), no ≤4-mirror shortcut. */
export const PUZZLE_044: Puzzle = {
  id: 44,
  code: "50376",
  gridSize: 6,
  source: { x: 2, y: 5, direction: "up" },
  flag: { x: 5, y: 2 },
  numbers: [
    { value: 5, x: 3, y: 5 },
    { value: 0, x: 4, y: 3 },
    { value: 3, x: 3, y: 2 },
    { value: 7, x: 0, y: 3 },
    { value: 6, x: 1, y: 0 },
  ],
  obstacles: [
    { x: 0, y: 5 },
    { x: 5, y: 5 },
  ],
};
