import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts — do not edit by hand.
/** Scheduled 2026-07-27 (extra hard). 9×9, 8-digit code, intended 31-mirror solution (38% density), no ≤3-mirror shortcut. */
export const PUZZLE_036: Puzzle = {
  id: 36,
  code: "47964380",
  gridSize: 9,
  source: { x: 4, y: 6, direction: "up" },
  flag: { x: 7, y: 7 },
  numbers: [
    { value: 4, x: 5, y: 5 },
    { value: 7, x: 6, y: 6 },
    { value: 9, x: 2, y: 8 },
    { value: 6, x: 1, y: 3 },
    { value: 4, x: 0, y: 4 },
    { value: 3, x: 5, y: 3 },
    { value: 8, x: 8, y: 4 },
    { value: 0, x: 7, y: 6 },
  ],
  obstacles: [
    { x: 5, y: 4 },
    { x: 0, y: 2 },
    { x: 5, y: 1 },
    { x: 6, y: 0 },
    { x: 7, y: 0 },
  ],
};
