import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts. Do not edit by hand.
/** Scheduled 2026-09-21 (extra hard). 6×6, 6-digit code, intended 16-mirror solution (44% density), no ≤4-mirror shortcut. */
export const PUZZLE_092: Puzzle = {
  id: 92,
  code: "198799",
  gridSize: 6,
  source: { x: 0, y: 4, direction: "right" },
  flag: { x: 5, y: 2 },
  numbers: [
    { value: 1, x: 2, y: 3 },
    { value: 9, x: 4, y: 3 },
    { value: 8, x: 1, y: 2 },
    { value: 7, x: 0, y: 2 },
    { value: 9, x: 1, y: 0 },
    { value: 9, x: 5, y: 1 },
  ],
  obstacles: [
    { x: 0, y: 5 },
    { x: 4, y: 1 },
  ],
};
