import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts — do not edit by hand.
/** Scheduled 2026-08-15 (extra hard). 5×5, 4-digit code, intended 10-mirror solution (40% density), no ≤6-mirror shortcut. */
export const PUZZLE_055: Puzzle = {
  id: 55,
  code: "5860",
  gridSize: 5,
  source: { x: 1, y: 3, direction: "up" },
  flag: { x: 1, y: 0 },
  numbers: [
    { value: 5, x: 2, y: 2 },
    { value: 8, x: 4, y: 2 },
    { value: 6, x: 3, y: 2 },
    { value: 0, x: 2, y: 0 },
  ],
  obstacles: [
    { x: 1, y: 1 },
    { x: 3, y: 4 },
  ],
};
