import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts — do not edit by hand.
/** Scheduled 2026-08-06 (extra hard). 8×8, 6-digit code, intended 24-mirror solution (38% density), no ≤3-mirror shortcut. */
export const PUZZLE_046: Puzzle = {
  id: 46,
  code: "958283",
  gridSize: 8,
  source: { x: 0, y: 4, direction: "right" },
  flag: { x: 2, y: 4 },
  numbers: [
    { value: 9, x: 2, y: 5 },
    { value: 5, x: 2, y: 6 },
    { value: 8, x: 1, y: 1 },
    { value: 2, x: 3, y: 0 },
    { value: 8, x: 6, y: 2 },
    { value: 3, x: 2, y: 2 },
  ],
  obstacles: [
    { x: 5, y: 0 },
    { x: 1, y: 7 },
    { x: 0, y: 6 },
    { x: 6, y: 1 },
  ],
};
