import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts — do not edit by hand.
/** Scheduled 2026-07-25 (extra hard). 5×5, 4-digit code, intended 12-mirror solution (48% density), no ≤6-mirror shortcut. */
export const PUZZLE_034: Puzzle = {
  id: 34,
  code: "3860",
  gridSize: 5,
  source: { x: 1, y: 1, direction: "right" },
  flag: { x: 4, y: 2 },
  numbers: [
    { value: 3, x: 1, y: 3 },
    { value: 8, x: 1, y: 2 },
    { value: 6, x: 3, y: 4 },
    { value: 0, x: 4, y: 3 },
  ],
  obstacles: [
    { x: 1, y: 4 },
    { x: 0, y: 1 },
  ],
};
