import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts — do not edit by hand.
/** Scheduled 2026-08-26 (extra hard). 5×5, 5-digit code, intended 11-mirror solution (44% density), no ≤6-mirror shortcut. */
export const PUZZLE_066: Puzzle = {
  id: 66,
  code: "20160",
  gridSize: 5,
  source: { x: 3, y: 4, direction: "up" },
  flag: { x: 0, y: 2 },
  numbers: [
    { value: 2, x: 4, y: 2 },
    { value: 0, x: 2, y: 2 },
    { value: 1, x: 1, y: 2 },
    { value: 6, x: 1, y: 0 },
    { value: 0, x: 0, y: 1 },
  ],
  obstacles: [
    { x: 2, y: 4 },
    { x: 3, y: 2 },
  ],
};
