import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts — do not edit by hand.
/** Scheduled 2026-07-25 (extra hard). 6×6, 5-digit code, intended 17-mirror solution (47% density), no ≤4-mirror shortcut. */
export const PUZZLE_034: Puzzle = {
  id: 34,
  code: "28537",
  gridSize: 6,
  source: { x: 1, y: 4, direction: "up" },
  flag: { x: 3, y: 5 },
  numbers: [
    { value: 2, x: 2, y: 2 },
    { value: 8, x: 3, y: 1 },
    { value: 5, x: 2, y: 3 },
    { value: 3, x: 4, y: 1 },
    { value: 7, x: 5, y: 1 },
  ],
  obstacles: [
    { x: 0, y: 1 },
    { x: 1, y: 0 },
  ],
};
