import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts — do not edit by hand.
/** Scheduled 2026-07-23 (extra hard). 4×4, 4-digit code, intended 6-mirror solution (38% density), no ≤5-mirror shortcut. */
export const PUZZLE_032: Puzzle = {
  id: 32,
  code: "9154",
  gridSize: 4,
  source: { x: 3, y: 1, direction: "left" },
  flag: { x: 2, y: 3 },
  numbers: [
    { value: 9, x: 0, y: 2 },
    { value: 1, x: 1, y: 2 },
    { value: 5, x: 2, y: 0 },
    { value: 4, x: 3, y: 2 },
  ],
  obstacles: [
    { x: 2, y: 2 },
  ],
};
