import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts — do not edit by hand.
/** Scheduled 2026-08-29 (extra hard). 6×6, 5-digit code, intended 13-mirror solution (36% density), no ≤4-mirror shortcut. */
export const PUZZLE_069: Puzzle = {
  id: 69,
  code: "10096",
  gridSize: 6,
  source: { x: 2, y: 1, direction: "down" },
  flag: { x: 1, y: 4 },
  numbers: [
    { value: 1, x: 1, y: 1 },
    { value: 0, x: 0, y: 2 },
    { value: 0, x: 1, y: 5 },
    { value: 9, x: 3, y: 4 },
    { value: 6, x: 3, y: 3 },
  ],
  obstacles: [
    { x: 2, y: 0 },
    { x: 3, y: 5 },
  ],
};
