import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts. Do not edit by hand.
/** Scheduled 2026-09-26 (extra hard). 6×6, 4-digit code, intended 14-mirror solution (39% density), no ≤4-mirror shortcut. */
export const PUZZLE_097: Puzzle = {
  id: 97,
  code: "9410",
  gridSize: 6,
  source: { x: 2, y: 3, direction: "left" },
  flag: { x: 0, y: 3 },
  numbers: [
    { value: 9, x: 1, y: 1 },
    { value: 4, x: 0, y: 1 },
    { value: 1, x: 3, y: 1 },
    { value: 0, x: 2, y: 1 },
  ],
  obstacles: [
    { x: 4, y: 0 },
    { x: 0, y: 5 },
  ],
};
