import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts. Do not edit by hand.
/** Scheduled 2026-09-07 (extra hard). 6×6, 5-digit code, intended 15-mirror solution (42% density), no ≤4-mirror shortcut. */
export const PUZZLE_078: Puzzle = {
  id: 78,
  code: "50796",
  gridSize: 6,
  source: { x: 5, y: 1, direction: "left" },
  flag: { x: 5, y: 3 },
  numbers: [
    { value: 5, x: 1, y: 5 },
    { value: 0, x: 0, y: 4 },
    { value: 7, x: 4, y: 5 },
    { value: 9, x: 4, y: 4 },
    { value: 6, x: 4, y: 0 },
  ],
  obstacles: [
    { x: 0, y: 2 },
    { x: 2, y: 0 },
  ],
};
