import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts — do not edit by hand.
/** Scheduled 2026-07-24 (extra hard). 5×5, 5-digit code, intended 10-mirror solution (40% density), no ≤6-mirror shortcut. */
export const PUZZLE_033: Puzzle = {
  id: 33,
  code: "28349",
  gridSize: 5,
  source: { x: 3, y: 0, direction: "down" },
  flag: { x: 0, y: 2 },
  numbers: [
    { value: 2, x: 2, y: 0 },
    { value: 8, x: 1, y: 2 },
    { value: 3, x: 2, y: 3 },
    { value: 4, x: 2, y: 4 },
    { value: 9, x: 0, y: 3 },
  ],
  obstacles: [
    { x: 3, y: 2 },
    { x: 4, y: 2 },
  ],
};
