import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts, do not edit by hand.
/** Scheduled 2026-08-10 (extra hard). 6×6, 4-digit code, intended 13-mirror solution (36% density), no ≤4-mirror shortcut. */
export const PUZZLE_050: Puzzle = {
  id: 50,
  code: "2065",
  gridSize: 6,
  source: { x: 1, y: 4, direction: "down" },
  flag: { x: 2, y: 0 },
  numbers: [
    { value: 2, x: 4, y: 3 },
    { value: 0, x: 4, y: 2 },
    { value: 6, x: 0, y: 1 },
    { value: 5, x: 2, y: 3 },
  ],
  obstacles: [
    { x: 4, y: 0 },
    { x: 3, y: 5 },
  ],
};
