import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts — do not edit by hand.
/** Scheduled 2026-07-15 (extra hard). 5×5, 4-digit code, intended 12-mirror solution (48% density), no ≤5-mirror shortcut. */
export const PUZZLE_024: Puzzle = {
  id: 24,
  code: "4181",
  gridSize: 5,
  source: { x: 1, y: 2, direction: "right" },
  flag: { x: 4, y: 2 },
  numbers: [
    { value: 4, x: 3, y: 4 },
    { value: 1, x: 0, y: 3 },
    { value: 8, x: 1, y: 0 },
    { value: 1, x: 4, y: 1 },
  ],
  obstacles: [
    { x: 3, y: 1 },
  ],
};
