import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts, do not edit by hand.
/** Scheduled 2026-08-09 (extra hard). 8×8, 6-digit code, intended 26-mirror solution (41% density), no ≤3-mirror shortcut. */
export const PUZZLE_049: Puzzle = {
  id: 49,
  code: "302687",
  gridSize: 8,
  source: { x: 7, y: 1, direction: "left" },
  flag: { x: 0, y: 5 },
  numbers: [
    { value: 3, x: 5, y: 0 },
    { value: 0, x: 6, y: 2 },
    { value: 2, x: 5, y: 5 },
    { value: 6, x: 1, y: 2 },
    { value: 8, x: 7, y: 4 },
    { value: 7, x: 6, y: 7 },
  ],
  obstacles: [
    { x: 2, y: 6 },
    { x: 6, y: 5 },
    { x: 6, y: 6 },
    { x: 1, y: 4 },
  ],
};
