import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts, do not edit by hand.
/** Scheduled 2026-08-03 (extra hard). 5×5, 6-digit code, intended 11-mirror solution (44% density), no ≤7-mirror shortcut. */
export const PUZZLE_043: Puzzle = {
  id: 43,
  code: "500150",
  gridSize: 5,
  source: { x: 1, y: 0, direction: "down" },
  flag: { x: 0, y: 2 },
  numbers: [
    { value: 5, x: 2, y: 0 },
    { value: 0, x: 2, y: 1 },
    { value: 0, x: 2, y: 2 },
    { value: 1, x: 3, y: 3 },
    { value: 5, x: 2, y: 4 },
    { value: 0, x: 0, y: 3 },
  ],
  obstacles: [
    { x: 1, y: 3 },
    { x: 2, y: 3 },
  ],
};
