import type { Puzzle } from "@/lib/puzzleTypes";

// AUTO-GENERATED by scripts/puzzles/generate.ts, do not edit by hand.
/** Scheduled 2026-08-05 (extra hard). 8×8, 6-digit code, intended 22-mirror solution (34% density), no ≤3-mirror shortcut. */
export const PUZZLE_045: Puzzle = {
  id: 45,
  code: "278001",
  gridSize: 8,
  source: { x: 0, y: 2, direction: "right" },
  flag: { x: 1, y: 3 },
  numbers: [
    { value: 2, x: 2, y: 1 },
    { value: 7, x: 4, y: 3 },
    { value: 8, x: 6, y: 3 },
    { value: 0, x: 7, y: 3 },
    { value: 0, x: 4, y: 4 },
    { value: 1, x: 2, y: 4 },
  ],
  obstacles: [
    { x: 7, y: 5 },
    { x: 5, y: 6 },
    { x: 3, y: 5 },
    { x: 7, y: 1 },
  ],
};
