/**
 * Codegen: turn generated puzzle data into committed source files.
 *
 * Everything the app imports is regenerated wholesale from a source of truth
 * (src/data/schedule.json + the draft files) rather than append-patched, so the
 * output is deterministic and diff-friendly.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { MirrorPlacement, Puzzle } from "../../src/lib/puzzleTypes";
import type { GeneratedPuzzle } from "./generator";

export const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const DATA_DIR = join(REPO_ROOT, "src", "data");
const DRAFTS_DIR = join(DATA_DIR, "drafts");
const SOLUTIONS_DIR = join(REPO_ROOT, "content", "solutions");
export const SCHEDULE_JSON = join(DATA_DIR, "schedule.json");

/** id → PUZZLE_NNN symbol / puzzle-NNN filename stem (3-digit zero-padded). */
export function puzzleStem(id: number): string {
  return `puzzle-${String(id).padStart(3, "0")}`;
}
export function puzzleSymbol(id: number): string {
  return `PUZZLE_${String(id).padStart(3, "0")}`;
}

const GENERATED_HEADER =
  "// AUTO-GENERATED by scripts/puzzles/generate.ts — do not edit by hand.";

function serializePuzzleBody(puzzle: Puzzle): string {
  const numbers = puzzle.numbers
    .map((n) => `    { value: ${n.value}, x: ${n.x}, y: ${n.y} },`)
    .join("\n");
  const obstacles = puzzle.obstacles
    .map((o) => `    { x: ${o.x}, y: ${o.y} },`)
    .join("\n");
  return [
    `  id: ${puzzle.id},`,
    `  code: ${JSON.stringify(puzzle.code)},`,
    `  gridSize: ${puzzle.gridSize},`,
    `  source: { x: ${puzzle.source.x}, y: ${puzzle.source.y}, direction: ${JSON.stringify(
      puzzle.source.direction
    )} },`,
    `  flag: { x: ${puzzle.flag.x}, y: ${puzzle.flag.y} },`,
    `  numbers: [\n${numbers}\n  ],`,
    `  obstacles: [${obstacles ? `\n${obstacles}\n  ` : ""}],`,
  ].join("\n");
}

export function writeDraftFile(
  puzzle: Puzzle,
  scheduledDate: string,
  generated: GeneratedPuzzle
): void {
  const area = puzzle.gridSize * puzzle.gridSize;
  const density = ((generated.solution.length / area) * 100).toFixed(0);
  const content = `import type { Puzzle } from "@/lib/puzzleTypes";

${GENERATED_HEADER}
/** Scheduled ${scheduledDate} (extra hard). ${puzzle.gridSize}×${puzzle.gridSize}, ${puzzle.code.length}-digit code, intended ${generated.solution.length}-mirror solution (${density}% density), no ≤${generated.grade.cap}-mirror shortcut. */
export const ${puzzleSymbol(puzzle.id)}: Puzzle = {
${serializePuzzleBody(puzzle)}
};
`;
  writeFileSync(join(DRAFTS_DIR, `${puzzleStem(puzzle.id)}.ts`), content);
}

export interface SolutionSidecar {
  id: number;
  scheduledDate: string;
  code: string;
  gridSize: number;
  seed: string;
  solutionMirrors: MirrorPlacement[];
  mirrorCount: number;
  mirrorDensity: number | null;
  solverCap: number;
  /** Exact minimum mirror count, when a full search found one within the cap. */
  minMirrors?: number;
  /** Lower bound (cap + 1) when no solution was found within the cap. */
  minMirrorsAtLeast?: number;
  pathLength: number | null;
  obstacleInterference: number;
  score: number;
}

export function writeSolutionSidecar(sidecar: SolutionSidecar): void {
  if (!existsSync(SOLUTIONS_DIR)) mkdirSync(SOLUTIONS_DIR, { recursive: true });
  writeFileSync(
    join(SOLUTIONS_DIR, `${puzzleStem(sidecar.id)}.json`),
    JSON.stringify(sidecar, null, 2) + "\n"
  );
}

/** PUZZLE_001 is defined inline; every other registered id is imported from a draft. */
const INLINE_PUZZLE_001 = `export const PUZZLE_001: Puzzle = {
  id: 1,
  code: "1234",
  gridSize: 7,
  source: { x: 0, y: 3, direction: "right" },
  flag: { x: 6, y: 3 },
  numbers: [
    { value: 1, x: 2, y: 1 },
    { value: 2, x: 4, y: 2 },
    { value: 3, x: 2, y: 5 },
    { value: 4, x: 5, y: 4 },
  ],
  obstacles: [
    { x: 1, y: 1 },
    { x: 3, y: 3 },
    { x: 5, y: 1 },
    { x: 4, y: 5 },
    { x: 1, y: 5 },
  ],
};`;

/** Regenerate src/data/puzzles.ts from the ordered list of registered draft ids. */
export function writePuzzlesIndex(draftIds: number[]): void {
  const ordered = [...draftIds].sort((a, b) => a - b);
  const imports = ordered
    .map((id) => `import { ${puzzleSymbol(id)} } from "./drafts/${puzzleStem(id)}";`)
    .join("\n");
  const arrayEntries = ["  PUZZLE_001", ...ordered.map((id) => `  ${puzzleSymbol(id)}`)].join(
    ",\n"
  );
  const reExports = ordered
    .map((id) => `export { ${puzzleSymbol(id)} } from "./drafts/${puzzleStem(id)}";`)
    .join("\n");

  const content = `${GENERATED_HEADER}
import type { Puzzle } from "@/lib/puzzleTypes";
${imports}
import { getScheduledPuzzleId } from "./schedule";

${INLINE_PUZZLE_001}

export const PUZZLES: Puzzle[] = [
${arrayEntries},
];

${reExports}

export function getPuzzleById(id: number): Puzzle | undefined {
  return PUZZLES.find((p) => p.id === id);
}

export function getPuzzleByIndex(index: number): Puzzle {
  return PUZZLES[index] ?? PUZZLE_001;
}

export function getPuzzleForDate(date: Date): Puzzle | undefined {
  const id = getScheduledPuzzleId(date);
  if (id === undefined) return undefined;
  return getPuzzleById(id);
}
`;
  writeFileSync(join(DATA_DIR, "puzzles.ts"), content);
}

/** Regenerate src/data/schedule.ts from the schedule map. */
export function writeScheduleModule(schedule: Record<string, number>): void {
  const entries = Object.keys(schedule)
    .sort()
    .map((date) => `  ${JSON.stringify(date)}: ${schedule[date]},`)
    .join("\n");

  const content = `${GENERATED_HEADER}
// Source of truth: src/data/schedule.json
/** Maps calendar dates (YYYY-MM-DD) to puzzle ids. */
export const PUZZLE_SCHEDULE: Record<string, number> = {
${entries}
};

export function formatDateKey(date: Date): string {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return \`\${year}-\${month}-\${day}\`;
}

export function getScheduledPuzzleId(date: Date): number | undefined {
  return PUZZLE_SCHEDULE[formatDateKey(date)];
}
`;
  writeFileSync(join(DATA_DIR, "schedule.ts"), content);
}

export function readScheduleJson(): Record<string, number> | null {
  if (!existsSync(SCHEDULE_JSON)) return null;
  return JSON.parse(readFileSync(SCHEDULE_JSON, "utf8"));
}

export function writeScheduleJson(schedule: Record<string, number>): void {
  const sorted: Record<string, number> = {};
  for (const date of Object.keys(schedule).sort()) sorted[date] = schedule[date];
  writeFileSync(SCHEDULE_JSON, JSON.stringify(sorted, null, 2) + "\n");
}
