/**
 * App-readable min-mirror stats.
 *
 * Builds src/data/puzzleStats.json — a map of puzzle id → known min-mirror data
 * the app uses for share efficiency. Autogenerated puzzles read their values
 * from the solution sidecars (content/solutions/puzzle-NNN.json); hand-made
 * puzzles without a sidecar are graded on the spot with the real engine.
 *
 * Run: `npm run puzzles:stats`.
 */

import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { PUZZLES } from "@/data/puzzles";
import { grade } from "./grader";
import { REPO_ROOT } from "./codegen";

const SOLUTIONS_DIR = join(REPO_ROOT, "content", "solutions");
const STATS_FILE = join(REPO_ROOT, "src", "data", "puzzleStats.json");

interface PuzzleStat {
  minMirrors?: number;
  minMirrorsAtLeast?: number;
}

/** Min-mirror data from the generated solution sidecars, keyed by puzzle id. */
function readSidecarStats(): Map<number, PuzzleStat> {
  const map = new Map<number, PuzzleStat>();
  if (!existsSync(SOLUTIONS_DIR)) return map;

  for (const file of readdirSync(SOLUTIONS_DIR)) {
    if (!file.endsWith(".json")) continue;
    const sidecar = JSON.parse(readFileSync(join(SOLUTIONS_DIR, file), "utf8"));
    if (typeof sidecar.id !== "number") continue;

    const stat: PuzzleStat = {};
    if (typeof sidecar.minMirrors === "number") {
      stat.minMirrors = sidecar.minMirrors;
    } else if (typeof sidecar.minMirrorsAtLeast === "number") {
      stat.minMirrorsAtLeast = sidecar.minMirrorsAtLeast;
    }
    if (stat.minMirrors !== undefined || stat.minMirrorsAtLeast !== undefined) {
      map.set(sidecar.id, stat);
    }
  }
  return map;
}

const sidecarStats = readSidecarStats();
const stats: Record<number, PuzzleStat> = {};

for (const puzzle of PUZZLES) {
  const fromSidecar = sidecarStats.get(puzzle.id);
  if (fromSidecar) {
    stats[puzzle.id] = fromSidecar;
    console.log(`#${puzzle.id} (sidecar): ${JSON.stringify(fromSidecar)}`);
    continue;
  }

  const g = grade(puzzle);
  stats[puzzle.id] = g.solvableWithinCap
    ? { minMirrors: g.minMirrors }
    : { minMirrorsAtLeast: g.cap + 1 };
  console.log(`#${puzzle.id} (graded): ${JSON.stringify(stats[puzzle.id])}`);
}

// Stable, ascending id order for a diff-friendly file.
const ordered: Record<number, PuzzleStat> = {};
for (const id of Object.keys(stats)
  .map(Number)
  .sort((a, b) => a - b)) {
  ordered[id] = stats[id];
}

writeFileSync(STATS_FILE, JSON.stringify(ordered, null, 2) + "\n");
console.log(`\nWrote ${Object.keys(ordered).length} puzzle stats → ${STATS_FILE}`);
