/**
 * App-readable min-mirror stats.
 *
 * Builds src/data/puzzleStats.json, a map of puzzle id → known min-mirror data
 * the app uses for share efficiency.
 *
 *   npm run puzzles:stats
 *       Fast baseline. Each puzzle takes its exact minimum from the solution
 *       sidecar (autogenerated) when present, keeps any exact value already in
 *       the file, and otherwise records the cheap grader's lower bound. Never
 *       downgrades an existing exact `minMirrors` to a bound.
 *
 *   npm run puzzles:stats -- --exact [--ids=16,17] [--force] [--budget=N] [--node-cap=N] [--minutes=N]
 *       Runs the beam-guided exact-min solver (exactMin.ts) to UPGRADE lower
 *       bounds to exact minimums where it can. Slow, target ids while backfilling.
 *       --force recomputes ids that already have an exact value.
 *       --minutes=N caps the solve time PER targeted id (each gets its own
 *       wall-clock slice, so one hard puzzle can't starve the rest); total run
 *       time ≈ N × (targeted ids needing a solve). The solver stops gracefully
 *       and records the best bound it proved. Pair with a huge --node-cap to let
 *       time be the only limiter. A time-limited run never lowers an existing bound.
 */

import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { PUZZLES } from "@/data/puzzles";
import { grade } from "./grader";
import { solveExactMin } from "./exactMin";
import { REPO_ROOT } from "./codegen";
import {
  SOLUTIONS_FILE,
  mergeSolution,
  readSolutions,
  writeSolutionsOrdered,
} from "./solutionsStore";

const SOLUTIONS_DIR = join(REPO_ROOT, "content", "solutions");
const STATS_FILE = join(REPO_ROOT, "src", "data", "puzzleStats.json");

interface PuzzleStat {
  minMirrors?: number;
  minMirrorsAtLeast?: number;
}

interface Args {
  exact: boolean;
  force: boolean;
  ids: Set<number> | null;
  budget: number | undefined;
  nodeCap: number | undefined;
  minutes: number | undefined;
}

function parseArgs(): Args {
  const args: Args = {
    exact: false,
    force: false,
    ids: null,
    budget: undefined,
    nodeCap: undefined,
    minutes: undefined,
  };
  for (const arg of process.argv.slice(2)) {
    if (arg === "--exact") args.exact = true;
    else if (arg === "--force") args.force = true;
    else if (arg.startsWith("--ids="))
      args.ids = new Set(arg.slice("--ids=".length).split(",").map(Number));
    else if (arg.startsWith("--budget=")) args.budget = Number(arg.slice("--budget=".length));
    else if (arg.startsWith("--node-cap=")) args.nodeCap = Number(arg.slice("--node-cap=".length));
    else if (arg.startsWith("--minutes=")) args.minutes = Number(arg.slice("--minutes=".length));
  }
  return args;
}

/** Exact `minMirrors` from the generated solution sidecars, keyed by puzzle id. */
function readSidecarStats(): Map<number, PuzzleStat> {
  const map = new Map<number, PuzzleStat>();
  if (!existsSync(SOLUTIONS_DIR)) return map;

  for (const file of readdirSync(SOLUTIONS_DIR)) {
    if (!file.endsWith(".json")) continue;
    const sidecar = JSON.parse(readFileSync(join(SOLUTIONS_DIR, file), "utf8"));
    if (typeof sidecar.id !== "number") continue;

    const stat: PuzzleStat = {};
    if (typeof sidecar.minMirrors === "number") stat.minMirrors = sidecar.minMirrors;
    else if (typeof sidecar.minMirrorsAtLeast === "number")
      stat.minMirrorsAtLeast = sidecar.minMirrorsAtLeast;
    if (stat.minMirrors !== undefined || stat.minMirrorsAtLeast !== undefined) {
      map.set(sidecar.id, stat);
    }
  }
  return map;
}

function readExistingStats(): Record<number, PuzzleStat> {
  if (!existsSync(STATS_FILE)) return {};
  try {
    return JSON.parse(readFileSync(STATS_FILE, "utf8"));
  } catch {
    return {};
  }
}

const args = parseArgs();
const sidecarStats = readSidecarStats();
const cache = readExistingStats();
// Seed from the existing file so the on-disk map is always complete, even when
// we flush mid-run (a long --exact pass may be interrupted before the last id).
const stats: Record<number, PuzzleStat> = { ...cache };

function writeStats(): void {
  const ordered: Record<number, PuzzleStat> = {};
  for (const id of Object.keys(stats)
    .map(Number)
    .sort((a, b) => a - b)) {
    ordered[id] = stats[id];
  }
  writeFileSync(STATS_FILE, JSON.stringify(ordered, null, 2) + "\n");
}

for (const puzzle of PUZZLES) {
  const id = puzzle.id;

  // Baseline: sidecar exact → cheap grader bound.
  let stat = sidecarStats.get(id);
  if (!stat) {
    const g = grade(puzzle);
    stat = g.solvableWithinCap ? { minMirrors: g.minMirrors } : { minMirrorsAtLeast: g.cap + 1 };
  }

  // Never lose an exact value already recorded in the file.
  const cached = cache[id];
  if (cached?.minMirrors !== undefined && stat.minMirrors === undefined) {
    stat = { minMirrors: cached.minMirrors };
  }

  // Optional heavy exact-min upgrade.
  const targeted = args.ids === null || args.ids.has(id);
  const willSolve =
    args.exact && targeted && (stat.minMirrors === undefined || args.force);
  if (willSolve) {
    const t0 = Date.now();
    // Per-puzzle wall-clock budget: each targeted id gets its own --minutes
    // slice, so a hard puzzle can't starve the others. Total run time ≈
    // minutes × (number of targeted ids still needing a solve).
    const deadlineMs =
      args.minutes !== undefined ? Date.now() + args.minutes * 60_000 : undefined;
    const res = solveExactMin(puzzle, {
      maxBudget: args.budget,
      nodeCap: args.nodeCap,
      deadlineMs,
    });
    const secs = ((Date.now() - t0) / 1000).toFixed(1);
    if (res.minMirrors !== undefined) {
      stat = { minMirrors: res.minMirrors };
      if (res.solution) {
        const solutions = readSolutions();
        const merged = mergeSolution(solutions[id], res.solution);
        if (merged) {
          solutions[id] = merged;
          writeSolutionsOrdered(SOLUTIONS_FILE, solutions);
        }
      }
    } else {
      // A time/node-limited run can return a weaker bound than one already
      // recorded, never let it lower the best-known lower bound.
      const bound = Math.max(
        res.minMirrorsAtLeast ?? 0,
        stat.minMirrorsAtLeast ?? 0,
        cached?.minMirrorsAtLeast ?? 0
      );
      stat = { minMirrorsAtLeast: bound };
    }
    console.log(
      `#${id} exact: ${
        res.minMirrors !== undefined ? `${res.minMirrors} (min)` : `≥${res.minMirrorsAtLeast}`
      }  ${res.proven ? "proven" : "node-capped"}  ${secs}s  ${res.nodes.toLocaleString()} nodes`
    );
  } else {
    console.log(`#${id}: ${JSON.stringify(stat)}`);
  }

  stats[id] = stat;
  // Flush after each heavy solve so an interrupted long run keeps its progress.
  if (willSolve) writeStats();
}

writeStats();
console.log(`\nWrote ${Object.keys(stats).length} puzzle stats → ${STATS_FILE}`);
