/**
 * App-readable min-mirror stats.
 *
 * Builds src/data/puzzleStats.json — a map of puzzle id → known min-mirror data
 * the app uses for share efficiency.
 *
 *   npm run puzzles:stats
 *       Fast baseline. Each puzzle takes its exact minimum from the solution
 *       sidecar (autogenerated) when present, keeps any exact value already in
 *       the file, and otherwise records the cheap grader's lower bound. Never
 *       downgrades an existing exact `minMirrors` to a bound.
 *
 *   npm run puzzles:stats -- --exact [--ids=16,17] [--force] [--budget=N] [--node-cap=N]
 *       Runs the beam-guided exact-min solver (exactMin.ts) to UPGRADE lower
 *       bounds to exact minimums where it can. Slow — target ids while backfilling.
 *       --force recomputes ids that already have an exact value.
 */

import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { PUZZLES } from "@/data/puzzles";
import { grade } from "./grader";
import { solveExactMin } from "./exactMin";
import { REPO_ROOT } from "./codegen";

const SOLUTIONS_DIR = join(REPO_ROOT, "content", "solutions");
const STATS_FILE = join(REPO_ROOT, "src", "data", "puzzleStats.json");

interface PuzzleStat {
  minMirrors?: number;
  minMirrorsAtLeast?: number;
}

interface Args {
  exact: boolean;
  force: boolean;
  ids: Set<number> | null;
  budget: number | undefined;
  nodeCap: number | undefined;
}

function parseArgs(): Args {
  const args: Args = {
    exact: false,
    force: false,
    ids: null,
    budget: undefined,
    nodeCap: undefined,
  };
  for (const arg of process.argv.slice(2)) {
    if (arg === "--exact") args.exact = true;
    else if (arg === "--force") args.force = true;
    else if (arg.startsWith("--ids="))
      args.ids = new Set(arg.slice("--ids=".length).split(",").map(Number));
    else if (arg.startsWith("--budget=")) args.budget = Number(arg.slice("--budget=".length));
    else if (arg.startsWith("--node-cap=")) args.nodeCap = Number(arg.slice("--node-cap=".length));
  }
  return args;
}

/** Exact `minMirrors` from the generated solution sidecars, keyed by puzzle id. */
function readSidecarStats(): Map<number, PuzzleStat> {
  const map = new Map<number, PuzzleStat>();
  if (!existsSync(SOLUTIONS_DIR)) return map;

  for (const file of readdirSync(SOLUTIONS_DIR)) {
    if (!file.endsWith(".json")) continue;
    const sidecar = JSON.parse(readFileSync(join(SOLUTIONS_DIR, file), "utf8"));
    if (typeof sidecar.id !== "number") continue;

    const stat: PuzzleStat = {};
    if (typeof sidecar.minMirrors === "number") stat.minMirrors = sidecar.minMirrors;
    else if (typeof sidecar.minMirrorsAtLeast === "number")
      stat.minMirrorsAtLeast = sidecar.minMirrorsAtLeast;
    if (stat.minMirrors !== undefined || stat.minMirrorsAtLeast !== undefined) {
      map.set(sidecar.id, stat);
    }
  }
  return map;
}

function readExistingStats(): Record<number, PuzzleStat> {
  if (!existsSync(STATS_FILE)) return {};
  try {
    return JSON.parse(readFileSync(STATS_FILE, "utf8"));
  } catch {
    return {};
  }
}

const args = parseArgs();
const sidecarStats = readSidecarStats();
const cache = readExistingStats();
const stats: Record<number, PuzzleStat> = {};

for (const puzzle of PUZZLES) {
  const id = puzzle.id;

  // Baseline: sidecar exact → cheap grader bound.
  let stat = sidecarStats.get(id);
  if (!stat) {
    const g = grade(puzzle);
    stat = g.solvableWithinCap ? { minMirrors: g.minMirrors } : { minMirrorsAtLeast: g.cap + 1 };
  }

  // Never lose an exact value already recorded in the file.
  const cached = cache[id];
  if (cached?.minMirrors !== undefined && stat.minMirrors === undefined) {
    stat = { minMirrors: cached.minMirrors };
  }

  // Optional heavy exact-min upgrade.
  const targeted = args.ids === null || args.ids.has(id);
  if (args.exact && targeted && (stat.minMirrors === undefined || args.force)) {
    const t0 = Date.now();
    const res = solveExactMin(puzzle, { maxBudget: args.budget, nodeCap: args.nodeCap });
    const secs = ((Date.now() - t0) / 1000).toFixed(1);
    if (res.minMirrors !== undefined) {
      stat = { minMirrors: res.minMirrors };
    } else {
      const bound = Math.max(res.minMirrorsAtLeast ?? 0, stat.minMirrorsAtLeast ?? 0);
      stat = { minMirrorsAtLeast: bound };
    }
    console.log(
      `#${id} exact: ${
        res.minMirrors !== undefined ? `${res.minMirrors} (min)` : `≥${res.minMirrorsAtLeast}`
      }  ${res.proven ? "proven" : "node-capped"}  ${secs}s  ${res.nodes.toLocaleString()} nodes`
    );
  } else {
    console.log(`#${id}: ${JSON.stringify(stat)}`);
  }

  stats[id] = stat;
}

const ordered: Record<number, PuzzleStat> = {};
for (const id of Object.keys(stats)
  .map(Number)
  .sort((a, b) => a - b)) {
  ordered[id] = stats[id];
}

writeFileSync(STATS_FILE, JSON.stringify(ordered, null, 2) + "\n");
console.log(`\nWrote ${Object.keys(ordered).length} puzzle stats → ${STATS_FILE}`);
