// AUTO-GENERATED by scripts/puzzles/generate.ts — do not edit by hand.
import type { Puzzle } from "@/lib/puzzleTypes";
import { PUZZLE_002 } from "./drafts/puzzle-002";
import { PUZZLE_003 } from "./drafts/puzzle-003";
import { PUZZLE_004 } from "./drafts/puzzle-004";
import { PUZZLE_005 } from "./drafts/puzzle-005";
import { PUZZLE_006 } from "./drafts/puzzle-006";
import { PUZZLE_007 } from "./drafts/puzzle-007";
import { PUZZLE_008 } from "./drafts/puzzle-008";
import { PUZZLE_009 } from "./drafts/puzzle-009";
import { PUZZLE_010 } from "./drafts/puzzle-010";
import { PUZZLE_011 } from "./drafts/puzzle-011";
import { PUZZLE_012 } from "./drafts/puzzle-012";
import { PUZZLE_013 } from "./drafts/puzzle-013";
import { PUZZLE_014 } from "./drafts/puzzle-014";
import { PUZZLE_015 } from "./drafts/puzzle-015";
import { PUZZLE_016 } from "./drafts/puzzle-016";
import { PUZZLE_017 } from "./drafts/puzzle-017";
import { PUZZLE_018 } from "./drafts/puzzle-018";
import { PUZZLE_019 } from "./drafts/puzzle-019";
import { PUZZLE_020 } from "./drafts/puzzle-020";
import { PUZZLE_022 } from "./drafts/puzzle-022";
import { PUZZLE_023 } from "./drafts/puzzle-023";
import { PUZZLE_024 } from "./drafts/puzzle-024";
import { PUZZLE_025 } from "./drafts/puzzle-025";
import { PUZZLE_026 } from "./drafts/puzzle-026";
import { PUZZLE_027 } from "./drafts/puzzle-027";
import { PUZZLE_028 } from "./drafts/puzzle-028";
import { PUZZLE_029 } from "./drafts/puzzle-029";
import { PUZZLE_030 } from "./drafts/puzzle-030";
import { PUZZLE_031 } from "./drafts/puzzle-031";
import { PUZZLE_032 } from "./drafts/puzzle-032";
import { PUZZLE_033 } from "./drafts/puzzle-033";
import { PUZZLE_034 } from "./drafts/puzzle-034";
import { PUZZLE_035 } from "./drafts/puzzle-035";
import { PUZZLE_036 } from "./drafts/puzzle-036";
import { PUZZLE_037 } from "./drafts/puzzle-037";
import { PUZZLE_038 } from "./drafts/puzzle-038";
import { PUZZLE_039 } from "./drafts/puzzle-039";
import { PUZZLE_040 } from "./drafts/puzzle-040";
import { PUZZLE_041 } from "./drafts/puzzle-041";
import { PUZZLE_042 } from "./drafts/puzzle-042";
import { PUZZLE_043 } from "./drafts/puzzle-043";
import { PUZZLE_044 } from "./drafts/puzzle-044";
import { PUZZLE_045 } from "./drafts/puzzle-045";
import { PUZZLE_046 } from "./drafts/puzzle-046";
import { PUZZLE_047 } from "./drafts/puzzle-047";
import { PUZZLE_048 } from "./drafts/puzzle-048";
import { PUZZLE_049 } from "./drafts/puzzle-049";
import { PUZZLE_050 } from "./drafts/puzzle-050";
import { PUZZLE_051 } from "./drafts/puzzle-051";
import { PUZZLE_052 } from "./drafts/puzzle-052";
import { PUZZLE_053 } from "./drafts/puzzle-053";
import { PUZZLE_054 } from "./drafts/puzzle-054";
import { PUZZLE_055 } from "./drafts/puzzle-055";
import { PUZZLE_056 } from "./drafts/puzzle-056";
import { getScheduledPuzzleId } from "./schedule";

export const PUZZLE_001: Puzzle = {
  id: 1,
  code: "1234",
  gridSize: 7,
  source: { x: 0, y: 3, direction: "right" },
  flag: { x: 6, y: 3 },
  numbers: [
    { value: 1, x: 2, y: 1 },
    { value: 2, x: 4, y: 2 },
    { value: 3, x: 2, y: 5 },
    { value: 4, x: 5, y: 4 },
  ],
  obstacles: [
    { x: 1, y: 1 },
    { x: 3, y: 3 },
    { x: 5, y: 1 },
    { x: 4, y: 5 },
    { x: 1, y: 5 },
  ],
};

export const PUZZLES: Puzzle[] = [
  PUZZLE_001,
  PUZZLE_002,
  PUZZLE_003,
  PUZZLE_004,
  PUZZLE_005,
  PUZZLE_006,
  PUZZLE_007,
  PUZZLE_008,
  PUZZLE_009,
  PUZZLE_010,
  PUZZLE_011,
  PUZZLE_012,
  PUZZLE_013,
  PUZZLE_014,
  PUZZLE_015,
  PUZZLE_016,
  PUZZLE_017,
  PUZZLE_018,
  PUZZLE_019,
  PUZZLE_020,
  PUZZLE_022,
  PUZZLE_023,
  PUZZLE_024,
  PUZZLE_025,
  PUZZLE_026,
  PUZZLE_027,
  PUZZLE_028,
  PUZZLE_029,
  PUZZLE_030,
  PUZZLE_031,
  PUZZLE_032,
  PUZZLE_033,
  PUZZLE_034,
  PUZZLE_035,
  PUZZLE_036,
  PUZZLE_037,
  PUZZLE_038,
  PUZZLE_039,
  PUZZLE_040,
  PUZZLE_041,
  PUZZLE_042,
  PUZZLE_043,
  PUZZLE_044,
  PUZZLE_045,
  PUZZLE_046,
  PUZZLE_047,
  PUZZLE_048,
  PUZZLE_049,
  PUZZLE_050,
  PUZZLE_051,
  PUZZLE_052,
  PUZZLE_053,
  PUZZLE_054,
  PUZZLE_055,
  PUZZLE_056,
];

export { PUZZLE_002 } from "./drafts/puzzle-002";
export { PUZZLE_003 } from "./drafts/puzzle-003";
export { PUZZLE_004 } from "./drafts/puzzle-004";
export { PUZZLE_005 } from "./drafts/puzzle-005";
export { PUZZLE_006 } from "./drafts/puzzle-006";
export { PUZZLE_007 } from "./drafts/puzzle-007";
export { PUZZLE_008 } from "./drafts/puzzle-008";
export { PUZZLE_009 } from "./drafts/puzzle-009";
export { PUZZLE_010 } from "./drafts/puzzle-010";
export { PUZZLE_011 } from "./drafts/puzzle-011";
export { PUZZLE_012 } from "./drafts/puzzle-012";
export { PUZZLE_013 } from "./drafts/puzzle-013";
export { PUZZLE_014 } from "./drafts/puzzle-014";
export { PUZZLE_015 } from "./drafts/puzzle-015";
export { PUZZLE_016 } from "./drafts/puzzle-016";
export { PUZZLE_017 } from "./drafts/puzzle-017";
export { PUZZLE_018 } from "./drafts/puzzle-018";
export { PUZZLE_019 } from "./drafts/puzzle-019";
export { PUZZLE_020 } from "./drafts/puzzle-020";
export { PUZZLE_022 } from "./drafts/puzzle-022";
export { PUZZLE_023 } from "./drafts/puzzle-023";
export { PUZZLE_024 } from "./drafts/puzzle-024";
export { PUZZLE_025 } from "./drafts/puzzle-025";
export { PUZZLE_026 } from "./drafts/puzzle-026";
export { PUZZLE_027 } from "./drafts/puzzle-027";
export { PUZZLE_028 } from "./drafts/puzzle-028";
export { PUZZLE_029 } from "./drafts/puzzle-029";
export { PUZZLE_030 } from "./drafts/puzzle-030";
export { PUZZLE_031 } from "./drafts/puzzle-031";
export { PUZZLE_032 } from "./drafts/puzzle-032";
export { PUZZLE_033 } from "./drafts/puzzle-033";
export { PUZZLE_034 } from "./drafts/puzzle-034";
export { PUZZLE_035 } from "./drafts/puzzle-035";
export { PUZZLE_036 } from "./drafts/puzzle-036";
export { PUZZLE_037 } from "./drafts/puzzle-037";
export { PUZZLE_038 } from "./drafts/puzzle-038";
export { PUZZLE_039 } from "./drafts/puzzle-039";
export { PUZZLE_040 } from "./drafts/puzzle-040";
export { PUZZLE_041 } from "./drafts/puzzle-041";
export { PUZZLE_042 } from "./drafts/puzzle-042";
export { PUZZLE_043 } from "./drafts/puzzle-043";
export { PUZZLE_044 } from "./drafts/puzzle-044";
export { PUZZLE_045 } from "./drafts/puzzle-045";
export { PUZZLE_046 } from "./drafts/puzzle-046";
export { PUZZLE_047 } from "./drafts/puzzle-047";
export { PUZZLE_048 } from "./drafts/puzzle-048";
export { PUZZLE_049 } from "./drafts/puzzle-049";
export { PUZZLE_050 } from "./drafts/puzzle-050";
export { PUZZLE_051 } from "./drafts/puzzle-051";
export { PUZZLE_052 } from "./drafts/puzzle-052";
export { PUZZLE_053 } from "./drafts/puzzle-053";
export { PUZZLE_054 } from "./drafts/puzzle-054";
export { PUZZLE_055 } from "./drafts/puzzle-055";
export { PUZZLE_056 } from "./drafts/puzzle-056";

export function getPuzzleById(id: number): Puzzle | undefined {
  return PUZZLES.find((p) => p.id === id);
}

export function getPuzzleByIndex(index: number): Puzzle {
  return PUZZLES[index] ?? PUZZLE_001;
}

export function getPuzzleForDate(date: Date): Puzzle | undefined {
  const id = getScheduledPuzzleId(date);
  if (id === undefined) return undefined;
  return getPuzzleById(id);
}
