// AUTO-GENERATED by scripts/puzzles/generate.ts. Do not edit by hand.
import type { Puzzle } from "@/lib/puzzleTypes";
import { PUZZLE_002 } from "./drafts/puzzle-002";
import { PUZZLE_003 } from "./drafts/puzzle-003";
import { PUZZLE_004 } from "./drafts/puzzle-004";
import { PUZZLE_005 } from "./drafts/puzzle-005";
import { PUZZLE_006 } from "./drafts/puzzle-006";
import { PUZZLE_007 } from "./drafts/puzzle-007";
import { PUZZLE_008 } from "./drafts/puzzle-008";
import { PUZZLE_009 } from "./drafts/puzzle-009";
import { PUZZLE_010 } from "./drafts/puzzle-010";
import { PUZZLE_011 } from "./drafts/puzzle-011";
import { PUZZLE_012 } from "./drafts/puzzle-012";
import { PUZZLE_013 } from "./drafts/puzzle-013";
import { PUZZLE_014 } from "./drafts/puzzle-014";
import { PUZZLE_015 } from "./drafts/puzzle-015";
import { PUZZLE_016 } from "./drafts/puzzle-016";
import { PUZZLE_017 } from "./drafts/puzzle-017";
import { PUZZLE_018 } from "./drafts/puzzle-018";
import { PUZZLE_019 } from "./drafts/puzzle-019";
import { PUZZLE_020 } from "./drafts/puzzle-020";
import { PUZZLE_022 } from "./drafts/puzzle-022";
import { PUZZLE_023 } from "./drafts/puzzle-023";
import { PUZZLE_024 } from "./drafts/puzzle-024";
import { PUZZLE_025 } from "./drafts/puzzle-025";
import { PUZZLE_026 } from "./drafts/puzzle-026";
import { PUZZLE_027 } from "./drafts/puzzle-027";
import { PUZZLE_028 } from "./drafts/puzzle-028";
import { PUZZLE_029 } from "./drafts/puzzle-029";
import { PUZZLE_030 } from "./drafts/puzzle-030";
import { PUZZLE_031 } from "./drafts/puzzle-031";
import { PUZZLE_032 } from "./drafts/puzzle-032";
import { PUZZLE_033 } from "./drafts/puzzle-033";
import { PUZZLE_034 } from "./drafts/puzzle-034";
import { PUZZLE_035 } from "./drafts/puzzle-035";
import { PUZZLE_036 } from "./drafts/puzzle-036";
import { PUZZLE_037 } from "./drafts/puzzle-037";
import { PUZZLE_038 } from "./drafts/puzzle-038";
import { PUZZLE_039 } from "./drafts/puzzle-039";
import { PUZZLE_040 } from "./drafts/puzzle-040";
import { PUZZLE_041 } from "./drafts/puzzle-041";
import { PUZZLE_042 } from "./drafts/puzzle-042";
import { PUZZLE_043 } from "./drafts/puzzle-043";
import { PUZZLE_044 } from "./drafts/puzzle-044";
import { PUZZLE_045 } from "./drafts/puzzle-045";
import { PUZZLE_046 } from "./drafts/puzzle-046";
import { PUZZLE_047 } from "./drafts/puzzle-047";
import { PUZZLE_048 } from "./drafts/puzzle-048";
import { PUZZLE_049 } from "./drafts/puzzle-049";
import { PUZZLE_050 } from "./drafts/puzzle-050";
import { PUZZLE_051 } from "./drafts/puzzle-051";
import { PUZZLE_052 } from "./drafts/puzzle-052";
import { PUZZLE_053 } from "./drafts/puzzle-053";
import { PUZZLE_054 } from "./drafts/puzzle-054";
import { PUZZLE_055 } from "./drafts/puzzle-055";
import { PUZZLE_056 } from "./drafts/puzzle-056";
import { PUZZLE_057 } from "./drafts/puzzle-057";
import { PUZZLE_058 } from "./drafts/puzzle-058";
import { PUZZLE_059 } from "./drafts/puzzle-059";
import { PUZZLE_060 } from "./drafts/puzzle-060";
import { PUZZLE_061 } from "./drafts/puzzle-061";
import { PUZZLE_062 } from "./drafts/puzzle-062";
import { PUZZLE_063 } from "./drafts/puzzle-063";
import { PUZZLE_064 } from "./drafts/puzzle-064";
import { PUZZLE_065 } from "./drafts/puzzle-065";
import { PUZZLE_066 } from "./drafts/puzzle-066";
import { PUZZLE_067 } from "./drafts/puzzle-067";
import { PUZZLE_068 } from "./drafts/puzzle-068";
import { PUZZLE_069 } from "./drafts/puzzle-069";
import { PUZZLE_070 } from "./drafts/puzzle-070";
import { PUZZLE_071 } from "./drafts/puzzle-071";
import { PUZZLE_072 } from "./drafts/puzzle-072";
import { PUZZLE_073 } from "./drafts/puzzle-073";
import { PUZZLE_074 } from "./drafts/puzzle-074";
import { PUZZLE_075 } from "./drafts/puzzle-075";
import { PUZZLE_076 } from "./drafts/puzzle-076";
import { PUZZLE_077 } from "./drafts/puzzle-077";
import { PUZZLE_078 } from "./drafts/puzzle-078";
import { PUZZLE_079 } from "./drafts/puzzle-079";
import { PUZZLE_080 } from "./drafts/puzzle-080";
import { PUZZLE_081 } from "./drafts/puzzle-081";
import { PUZZLE_082 } from "./drafts/puzzle-082";
import { PUZZLE_083 } from "./drafts/puzzle-083";
import { getScheduledPuzzleId } from "./schedule";

export const PUZZLE_001: Puzzle = {
  id: 1,
  code: "1234",
  gridSize: 7,
  source: { x: 0, y: 3, direction: "right" },
  flag: { x: 6, y: 3 },
  numbers: [
    { value: 1, x: 2, y: 1 },
    { value: 2, x: 4, y: 2 },
    { value: 3, x: 2, y: 5 },
    { value: 4, x: 5, y: 4 },
  ],
  obstacles: [
    { x: 1, y: 1 },
    { x: 3, y: 3 },
    { x: 5, y: 1 },
    { x: 4, y: 5 },
    { x: 1, y: 5 },
  ],
};

export const PUZZLES: Puzzle[] = [
  PUZZLE_001,
  PUZZLE_002,
  PUZZLE_003,
  PUZZLE_004,
  PUZZLE_005,
  PUZZLE_006,
  PUZZLE_007,
  PUZZLE_008,
  PUZZLE_009,
  PUZZLE_010,
  PUZZLE_011,
  PUZZLE_012,
  PUZZLE_013,
  PUZZLE_014,
  PUZZLE_015,
  PUZZLE_016,
  PUZZLE_017,
  PUZZLE_018,
  PUZZLE_019,
  PUZZLE_020,
  PUZZLE_022,
  PUZZLE_023,
  PUZZLE_024,
  PUZZLE_025,
  PUZZLE_026,
  PUZZLE_027,
  PUZZLE_028,
  PUZZLE_029,
  PUZZLE_030,
  PUZZLE_031,
  PUZZLE_032,
  PUZZLE_033,
  PUZZLE_034,
  PUZZLE_035,
  PUZZLE_036,
  PUZZLE_037,
  PUZZLE_038,
  PUZZLE_039,
  PUZZLE_040,
  PUZZLE_041,
  PUZZLE_042,
  PUZZLE_043,
  PUZZLE_044,
  PUZZLE_045,
  PUZZLE_046,
  PUZZLE_047,
  PUZZLE_048,
  PUZZLE_049,
  PUZZLE_050,
  PUZZLE_051,
  PUZZLE_052,
  PUZZLE_053,
  PUZZLE_054,
  PUZZLE_055,
  PUZZLE_056,
  PUZZLE_057,
  PUZZLE_058,
  PUZZLE_059,
  PUZZLE_060,
  PUZZLE_061,
  PUZZLE_062,
  PUZZLE_063,
  PUZZLE_064,
  PUZZLE_065,
  PUZZLE_066,
  PUZZLE_067,
  PUZZLE_068,
  PUZZLE_069,
  PUZZLE_070,
  PUZZLE_071,
  PUZZLE_072,
  PUZZLE_073,
  PUZZLE_074,
  PUZZLE_075,
  PUZZLE_076,
  PUZZLE_077,
  PUZZLE_078,
  PUZZLE_079,
  PUZZLE_080,
  PUZZLE_081,
  PUZZLE_082,
  PUZZLE_083,
];

export { PUZZLE_002 } from "./drafts/puzzle-002";
export { PUZZLE_003 } from "./drafts/puzzle-003";
export { PUZZLE_004 } from "./drafts/puzzle-004";
export { PUZZLE_005 } from "./drafts/puzzle-005";
export { PUZZLE_006 } from "./drafts/puzzle-006";
export { PUZZLE_007 } from "./drafts/puzzle-007";
export { PUZZLE_008 } from "./drafts/puzzle-008";
export { PUZZLE_009 } from "./drafts/puzzle-009";
export { PUZZLE_010 } from "./drafts/puzzle-010";
export { PUZZLE_011 } from "./drafts/puzzle-011";
export { PUZZLE_012 } from "./drafts/puzzle-012";
export { PUZZLE_013 } from "./drafts/puzzle-013";
export { PUZZLE_014 } from "./drafts/puzzle-014";
export { PUZZLE_015 } from "./drafts/puzzle-015";
export { PUZZLE_016 } from "./drafts/puzzle-016";
export { PUZZLE_017 } from "./drafts/puzzle-017";
export { PUZZLE_018 } from "./drafts/puzzle-018";
export { PUZZLE_019 } from "./drafts/puzzle-019";
export { PUZZLE_020 } from "./drafts/puzzle-020";
export { PUZZLE_022 } from "./drafts/puzzle-022";
export { PUZZLE_023 } from "./drafts/puzzle-023";
export { PUZZLE_024 } from "./drafts/puzzle-024";
export { PUZZLE_025 } from "./drafts/puzzle-025";
export { PUZZLE_026 } from "./drafts/puzzle-026";
export { PUZZLE_027 } from "./drafts/puzzle-027";
export { PUZZLE_028 } from "./drafts/puzzle-028";
export { PUZZLE_029 } from "./drafts/puzzle-029";
export { PUZZLE_030 } from "./drafts/puzzle-030";
export { PUZZLE_031 } from "./drafts/puzzle-031";
export { PUZZLE_032 } from "./drafts/puzzle-032";
export { PUZZLE_033 } from "./drafts/puzzle-033";
export { PUZZLE_034 } from "./drafts/puzzle-034";
export { PUZZLE_035 } from "./drafts/puzzle-035";
export { PUZZLE_036 } from "./drafts/puzzle-036";
export { PUZZLE_037 } from "./drafts/puzzle-037";
export { PUZZLE_038 } from "./drafts/puzzle-038";
export { PUZZLE_039 } from "./drafts/puzzle-039";
export { PUZZLE_040 } from "./drafts/puzzle-040";
export { PUZZLE_041 } from "./drafts/puzzle-041";
export { PUZZLE_042 } from "./drafts/puzzle-042";
export { PUZZLE_043 } from "./drafts/puzzle-043";
export { PUZZLE_044 } from "./drafts/puzzle-044";
export { PUZZLE_045 } from "./drafts/puzzle-045";
export { PUZZLE_046 } from "./drafts/puzzle-046";
export { PUZZLE_047 } from "./drafts/puzzle-047";
export { PUZZLE_048 } from "./drafts/puzzle-048";
export { PUZZLE_049 } from "./drafts/puzzle-049";
export { PUZZLE_050 } from "./drafts/puzzle-050";
export { PUZZLE_051 } from "./drafts/puzzle-051";
export { PUZZLE_052 } from "./drafts/puzzle-052";
export { PUZZLE_053 } from "./drafts/puzzle-053";
export { PUZZLE_054 } from "./drafts/puzzle-054";
export { PUZZLE_055 } from "./drafts/puzzle-055";
export { PUZZLE_056 } from "./drafts/puzzle-056";
export { PUZZLE_057 } from "./drafts/puzzle-057";
export { PUZZLE_058 } from "./drafts/puzzle-058";
export { PUZZLE_059 } from "./drafts/puzzle-059";
export { PUZZLE_060 } from "./drafts/puzzle-060";
export { PUZZLE_061 } from "./drafts/puzzle-061";
export { PUZZLE_062 } from "./drafts/puzzle-062";
export { PUZZLE_063 } from "./drafts/puzzle-063";
export { PUZZLE_064 } from "./drafts/puzzle-064";
export { PUZZLE_065 } from "./drafts/puzzle-065";
export { PUZZLE_066 } from "./drafts/puzzle-066";
export { PUZZLE_067 } from "./drafts/puzzle-067";
export { PUZZLE_068 } from "./drafts/puzzle-068";
export { PUZZLE_069 } from "./drafts/puzzle-069";
export { PUZZLE_070 } from "./drafts/puzzle-070";
export { PUZZLE_071 } from "./drafts/puzzle-071";
export { PUZZLE_072 } from "./drafts/puzzle-072";
export { PUZZLE_073 } from "./drafts/puzzle-073";
export { PUZZLE_074 } from "./drafts/puzzle-074";
export { PUZZLE_075 } from "./drafts/puzzle-075";
export { PUZZLE_076 } from "./drafts/puzzle-076";
export { PUZZLE_077 } from "./drafts/puzzle-077";
export { PUZZLE_078 } from "./drafts/puzzle-078";
export { PUZZLE_079 } from "./drafts/puzzle-079";
export { PUZZLE_080 } from "./drafts/puzzle-080";
export { PUZZLE_081 } from "./drafts/puzzle-081";
export { PUZZLE_082 } from "./drafts/puzzle-082";
export { PUZZLE_083 } from "./drafts/puzzle-083";

export function getPuzzleById(id: number): Puzzle | undefined {
  return PUZZLES.find((p) => p.id === id);
}

export function getPuzzleByIndex(index: number): Puzzle {
  return PUZZLES[index] ?? PUZZLE_001;
}

export function getPuzzleForDate(date: Date): Puzzle | undefined {
  const id = getScheduledPuzzleId(date);
  if (id === undefined) return undefined;
  return getPuzzleById(id);
}
